import HelmUI
import Module_Uninstaller_Engine

/// Localized strings for the Uninstaller module.
enum UnStr {
    static var moduleName: String { L("Uninstaller", [.ru: "Удаление приложений", .es: "Desinstalador", .fr: "Désinstalleur", .de: "Deinstallation", .ja: "アンインストーラ", .zh: "卸载器", .pt: "Desinstalador"]) }
    static var summary: String { L("Remove apps and all their leftover files", [.ru: "Удаление приложений со всеми хвостами", .es: "Elimina apps y todos sus archivos residuales", .fr: "Supprime les apps et tous leurs fichiers résiduels", .de: "Apps samt aller Restdateien entfernen", .ja: "アプリと残存ファイルをすべて削除", .zh: "删除应用及其所有残留文件", .pt: "Remove apps e todos os arquivos residuais"]) }
    static var searchApps: String { L("Search apps", [.ru: "Поиск приложений", .es: "Buscar apps", .fr: "Rechercher des apps", .de: "Apps suchen", .ja: "アプリを検索", .zh: "搜索应用", .pt: "Buscar apps"]) }
    static var loadingApps: String { L("Loading apps…", [.ru: "Загрузка приложений…", .es: "Cargando apps…", .fr: "Chargement des apps…", .de: "Apps werden geladen…", .ja: "アプリを読み込み中…", .zh: "正在加载应用…", .pt: "Carregando apps…"]) }
    static var scanning: String { L("Scanning…", [.ru: "Сканирование…", .es: "Analizando…", .fr: "Analyse…", .de: "Wird durchsucht…", .ja: "スキャン中…", .zh: "扫描中…", .pt: "Analisando…"]) }
    static var pickApp: String { L("Select an app to see what will be removed.", [.ru: "Выберите приложение, чтобы увидеть, что будет удалено.", .es: "Selecciona una app para ver qué se eliminará.", .fr: "Sélectionnez une app pour voir ce qui sera supprimé.", .de: "Wähle eine App, um zu sehen, was entfernt wird.", .ja: "削除対象を見るにはアプリを選択してください。", .zh: "选择一个应用以查看将删除的内容。", .pt: "Selecione um app para ver o que será removido."]) }
    static var theApp: String { L("Application", [.ru: "Приложение", .es: "Aplicación", .fr: "Application", .de: "Programm", .ja: "アプリケーション", .zh: "应用程序", .pt: "Aplicativo"]) }
    static var supportFiles: String { L("Supporting files", [.ru: "Дополнительные файлы", .es: "Archivos de soporte", .fr: "Fichiers annexes", .de: "Begleitdateien", .ja: "関連ファイル", .zh: "支持文件", .pt: "Arquivos de suporte"]) }
    static var moveToTrash: String { L("Move to Trash", [.ru: "Переместить в Корзину", .es: "Mover a la Papelera", .fr: "Placer dans la corbeille", .de: "In den Papierkorb", .ja: "ゴミ箱に入れる", .zh: "移到废纸篓", .pt: "Mover para o Lixo"]) }
    static var byName: String { L("by name", [.ru: "по имени", .es: "por nombre", .fr: "par nom", .de: "nach Name", .ja: "名前で一致", .zh: "按名称", .pt: "por nome"]) }
    static var nothingFound: String { L("No leftover files found.", [.ru: "Дополнительных файлов не найдено.", .es: "No se encontraron archivos residuales.", .fr: "Aucun fichier résiduel trouvé.", .de: "Keine Restdateien gefunden.", .ja: "残存ファイルは見つかりませんでした。", .zh: "未找到残留文件。", .pt: "Nenhum arquivo residual encontrado."]) }
    static func confirmTrash(_ count: Int, _ size: String) -> String { L("Move \(count) items (\(size)) to the Trash?", [.ru: "Переместить \(count) объектов (\(size)) в Корзину?", .es: "¿Mover \(count) elementos (\(size)) a la Papelera?", .fr: "Placer \(count) éléments (\(size)) dans la corbeille ?", .de: "\(count) Objekte (\(size)) in den Papierkorb legen?", .ja: "\(count) 項目 (\(size)) をゴミ箱に入れますか？", .zh: "将 \(count) 个项目（\(size)）移到废纸篓？", .pt: "Mover \(count) itens (\(size)) para o Lixo?"]) }
    static var appRunningTitle: String { L("App is running", [.ru: "Приложение запущено", .es: "La app está en ejecución", .fr: "L’app est en cours d’exécution", .de: "App läuft", .ja: "アプリが実行中です", .zh: "应用正在运行", .pt: "O app está em execução"]) }
    static var quitAndRemove: String { L("Quit & Remove", [.ru: "Закрыть и удалить", .es: "Salir y eliminar", .fr: "Quitter et supprimer", .de: "Beenden & entfernen", .ja: "終了して削除", .zh: "退出并删除", .pt: "Sair e remover"]) }
    static var cancel: String { L("Cancel", [.ru: "Отмена", .es: "Cancelar", .fr: "Annuler", .de: "Abbrechen", .ja: "キャンセル", .zh: "取消", .pt: "Cancelar"]) }
    static func freed(_ size: String) -> String { L("Freed \(size)", [.ru: "Освобождено \(size)", .es: "Liberado \(size)", .fr: "\(size) libérés", .de: "\(size) freigegeben", .ja: "\(size) を解放しました", .zh: "已释放 \(size)", .pt: "Liberado \(size)"]) }
    static func failedCount(_ n: Int) -> String { L("\(n) items could not be removed", [.ru: "Не удалось удалить объектов: \(n)", .es: "No se pudieron eliminar \(n) elementos", .fr: "\(n) éléments n’ont pas pu être supprimés", .de: "\(n) Objekte konnten nicht entfernt werden", .ja: "\(n) 項目を削除できませんでした", .zh: "\(n) 个项目无法删除", .pt: "\(n) itens não puderam ser removidos"]) }
    static var openInSettings: String { L("Open in Settings", [.ru: "Открыть в настройках", .es: "Abrir en Ajustes", .fr: "Ouvrir dans Réglages", .de: "In Einstellungen öffnen", .ja: "設定で開く", .zh: "在设置中打开", .pt: "Abrir nos Ajustes"]) }
    static var panelHint: String { L("Manage app removal in Settings.", [.ru: "Управление удалением — в настройках.", .es: "Gestiona la eliminación en Ajustes.", .fr: "Gérez la suppression dans Réglages.", .de: "Verwalte das Entfernen in den Einstellungen.", .ja: "削除の管理は設定で行います。", .zh: "在设置中管理删除。", .pt: "Gerencie a remoção nos Ajustes."]) }

    static func kind(_ k: LeftoverKind) -> String {
        switch k {
        case .appSupport: return L("Application Support", [.ru: "Данные приложения", .es: "Soporte de la app", .fr: "Données de l’app", .de: "App-Daten", .ja: "アプリのサポート", .zh: "应用支持", .pt: "Suporte do app"])
        case .caches: return L("Caches", [.ru: "Кеши", .es: "Cachés", .fr: "Caches", .de: "Caches", .ja: "キャッシュ", .zh: "缓存", .pt: "Caches"])
        case .preferences: return L("Preferences", [.ru: "Настройки", .es: "Preferencias", .fr: "Préférences", .de: "Einstellungen", .ja: "環境設定", .zh: "偏好设置", .pt: "Preferências"])
        case .containers: return L("Containers", [.ru: "Контейнеры", .es: "Contenedores", .fr: "Conteneurs", .de: "Container", .ja: "コンテナ", .zh: "容器", .pt: "Contêineres"])
        case .groupContainers: return L("Group Containers", [.ru: "Групповые контейнеры", .es: "Contenedores de grupo", .fr: "Conteneurs de groupe", .de: "Gruppencontainer", .ja: "グループコンテナ", .zh: "群组容器", .pt: "Contêineres de grupo"])
        case .savedState: return L("Saved State", [.ru: "Сохранённое состояние", .es: "Estado guardado", .fr: "État enregistré", .de: "Gespeicherter Zustand", .ja: "保存された状態", .zh: "保存的状态", .pt: "Estado salvo"])
        case .logs: return L("Logs", [.ru: "Логи", .es: "Registros", .fr: "Journaux", .de: "Protokolle", .ja: "ログ", .zh: "日志", .pt: "Registros"])
        case .httpStorages: return L("HTTP Storage", [.ru: "HTTP-хранилище", .es: "Almacenamiento HTTP", .fr: "Stockage HTTP", .de: "HTTP-Speicher", .ja: "HTTP ストレージ", .zh: "HTTP 存储", .pt: "Armazenamento HTTP"])
        case .webKit: return L("WebKit", [.ru: "WebKit", .es: "WebKit", .fr: "WebKit", .de: "WebKit", .ja: "WebKit", .zh: "WebKit", .pt: "WebKit"])
        case .cookies: return L("Cookies", [.ru: "Cookies", .es: "Cookies", .fr: "Cookies", .de: "Cookies", .ja: "Cookie", .zh: "Cookie", .pt: "Cookies"])
        case .appScripts: return L("Application Scripts", [.ru: "Скрипты приложения", .es: "Scripts de la app", .fr: "Scripts de l’app", .de: "App-Skripte", .ja: "アプリスクリプト", .zh: "应用脚本", .pt: "Scripts do app"])
        case .launchAgent: return L("Launch Agents", [.ru: "Агенты запуска", .es: "Agentes de inicio", .fr: "Agents de lancement", .de: "Startagenten", .ja: "起動エージェント", .zh: "启动代理", .pt: "Agentes de inicialização"])
        }
    }
    static var tabApps: String { L("Applications", [.ru: "Приложения", .es: "Aplicaciones", .fr: "Applications", .de: "Programme", .ja: "アプリケーション", .zh: "应用程序", .pt: "Aplicativos"]) }
    static var tabOrphans: String { L("Leftovers", [.ru: "Остатки", .es: "Restos", .fr: "Restes", .de: "Reste", .ja: "残存ファイル", .zh: "残留文件", .pt: "Restos"]) }
    static var orphansIntro: String { L("Find files left behind by apps that are no longer installed. Only files named after an app's bundle id are listed, and everything goes to the Trash.", [.ru: "Найти файлы, оставшиеся от уже удалённых приложений. В список попадают только файлы с именем bundle id приложения; всё удаляется в Корзину.", .es: "Encuentra archivos dejados por apps que ya no están instaladas. Solo se listan archivos con el bundle id de la app y todo va a la Papelera.", .fr: "Trouvez les fichiers laissés par des apps désinstallées. Seuls les fichiers nommés d’après le bundle id sont listés, et tout va à la corbeille.", .de: "Finde Dateien von Apps, die nicht mehr installiert sind. Nur Dateien mit der Bundle-ID der App werden gelistet, alles landet im Papierkorb.", .ja: "すでに削除されたアプリの残存ファイルを探します。bundle id 名のファイルのみを一覧表示し、すべてゴミ箱に移動します。", .zh: "查找已卸载应用遗留的文件。仅列出以应用 bundle id 命名的文件，全部移到废纸篓。", .pt: "Encontre arquivos deixados por apps que não estão mais instalados. Apenas arquivos nomeados com o bundle id são listados e tudo vai para o Lixo."]) }
    static var scanOrphans: String { L("Scan for leftovers", [.ru: "Найти остатки", .es: "Buscar restos", .fr: "Rechercher les restes", .de: "Nach Resten suchen", .ja: "残存ファイルを検索", .zh: "扫描残留文件", .pt: "Procurar restos"]) }
    static var scanningOrphans: String { L("Scanning…", [.ru: "Поиск…", .es: "Buscando…", .fr: "Analyse…", .de: "Suche…", .ja: "検索中…", .zh: "扫描中…", .pt: "Analisando…"]) }
    static var noOrphans: String { L("No leftovers found.", [.ru: "Остатков не найдено.", .es: "No se encontraron restos.", .fr: "Aucun reste trouvé.", .de: "Keine Reste gefunden.", .ja: "残存ファイルは見つかりませんでした。", .zh: "未发现残留文件。", .pt: "Nenhum resto encontrado."]) }
    static var selectAll: String { L("Select all", [.ru: "Выбрать всё", .es: "Seleccionar todo", .fr: "Tout sélectionner", .de: "Alle auswählen", .ja: "すべて選択", .zh: "全选", .pt: "Selecionar tudo"]) }
    static var deselectAll: String { L("Deselect all", [.ru: "Снять выделение", .es: "Deseleccionar todo", .fr: "Tout désélectionner", .de: "Auswahl aufheben", .ja: "選択をすべて解除", .zh: "取消全选", .pt: "Desmarcar tudo"]) }
    static var rescan: String { L("Scan again", [.ru: "Искать снова", .es: "Buscar de nuevo", .fr: "Relancer l’analyse", .de: "Erneut suchen", .ja: "再検索", .zh: "重新扫描", .pt: "Procurar novamente"]) }
    static func selectedSummary(_ n: Int, _ size: String) -> String { L("\(n) selected · \(size)", [.ru: "Выбрано: \(n) · \(size)", .es: "\(n) seleccionados · \(size)", .fr: "\(n) sélectionnés · \(size)", .de: "\(n) ausgewählt · \(size)", .ja: "\(n) 件選択 · \(size)", .zh: "已选 \(n) 项 · \(size)", .pt: "\(n) selecionados · \(size)"]) }
    static var metricApps: String { L("APPS", [.ru: "ПРИЛОЖЕНИЯ", .es: "APPS", .fr: "APPS", .de: "APPS", .ja: "アプリ", .zh: "应用", .pt: "APPS"]) }
    static var metricSize: String { L("SIZE", [.ru: "РАЗМЕР", .es: "TAMAÑO", .fr: "TAILLE", .de: "GRÖSSE", .ja: "サイズ", .zh: "大小", .pt: "TAMANHO"]) }
    static var metricLeftovers: String { L("LEFTOVERS", [.ru: "ОСТАТКИ", .es: "RESTOS", .fr: "RESTES", .de: "RESTE", .ja: "残存", .zh: "残留", .pt: "RESTOS"]) }
    static var metricChosen: String { L("CHOSEN", [.ru: "ВЫБРАНО", .es: "ELEGIDAS", .fr: "CHOISIES", .de: "GEWÄHLT", .ja: "選択", .zh: "已选", .pt: "ESCOLHIDAS"]) }
    static var selectNone: String { L("Clear selection", [.ru: "Снять выбор", .es: "Quitar selección", .fr: "Tout désélectionner", .de: "Auswahl aufheben", .ja: "選択を解除", .zh: "取消选择", .pt: "Limpar seleção"]) }
    static func reviewCount(_ n: Int) -> String { L("Review \(n)", [.ru: "Просмотреть: \(n)", .es: "Revisar \(n)", .fr: "Vérifier \(n)", .de: "\(n) prüfen", .ja: "\(n) 件を確認", .zh: "查看 \(n) 项", .pt: "Revisar \(n)"]) }
    static var back: String { L("Back", [.ru: "Назад", .es: "Atrás", .fr: "Retour", .de: "Zurück", .ja: "戻る", .zh: "返回", .pt: "Voltar"]) }
    static var removing: String { L("Removing…", [.ru: "Удаление…", .es: "Eliminando…", .fr: "Suppression…", .de: "Entferne…", .ja: "削除中…", .zh: "删除中…", .pt: "Removendo…"]) }
    static var noLeftoversForApp: String { L("No extra files found.", [.ru: "Дополнительных файлов не найдено.", .es: "No se encontraron archivos adicionales.", .fr: "Aucun fichier supplémentaire trouvé.", .de: "Keine zusätzlichen Dateien gefunden.", .ja: "追加ファイルは見つかりませんでした。", .zh: "未找到附加文件。", .pt: "Nenhum arquivo adicional encontrado."]) }
    static var runningBadge: String { L("Running", [.ru: "Запущено", .es: "En ejecución", .fr: "En cours", .de: "Läuft", .ja: "実行中", .zh: "运行中", .pt: "Em execução"]) }
    static func runningWarning(_ names: String) -> String { L("Still running: \(names). Quit to remove.", [.ru: "Ещё запущены: \(names). Для удаления нужно завершить.", .es: "Aún en ejecución: \(names). Hay que cerrarlas para eliminarlas.", .fr: "Encore en cours : \(names). À quitter pour les supprimer.", .de: "Läuft noch: \(names). Zum Entfernen beenden.", .ja: "実行中: \(names)。削除するには終了が必要です。", .zh: "仍在运行：\(names)。需先退出才能删除。", .pt: "Ainda em execução: \(names). É preciso encerrar para remover."]) }
    static var forceQuitAndRemove: String { L("Force quit and remove anyway", [.ru: "Завершить принудительно и удалить", .es: "Forzar salida y eliminar", .fr: "Forcer à quitter et supprimer", .de: "Sofort beenden und entfernen", .ja: "強制終了して削除", .zh: "强制退出并删除", .pt: "Forçar encerramento e remover"]) }
    static func willFree(_ size: String) -> String { L("Frees \(size)", [.ru: "Освободит \(size)", .es: "Libera \(size)", .fr: "Libère \(size)", .de: "Gibt \(size) frei", .ja: "\(size) を解放", .zh: "释放 \(size)", .pt: "Libera \(size)"]) }
    static func removedFreed(_ size: String) -> String { L("Removed — \(size) freed", [.ru: "Удалено — освобождено \(size)", .es: "Eliminado — \(size) liberados", .fr: "Supprimé — \(size) libérés", .de: "Entfernt — \(size) frei", .ja: "削除しました — \(size) を解放", .zh: "已删除 — 释放 \(size)", .pt: "Removido — \(size) liberados"]) }
    static func removedWithFailures(_ size: String, _ n: Int) -> String { L("Removed — \(size) freed, \(n) items could not be moved", [.ru: "Удалено — освобождено \(size), не удалось переместить: \(n)", .es: "Eliminado — \(size) liberados, \(n) elementos no se pudieron mover", .fr: "Supprimé — \(size) libérés, \(n) éléments non déplacés", .de: "Entfernt — \(size) frei, \(n) Objekte konnten nicht verschoben werden", .ja: "削除しました — \(size) を解放、\(n) 件は移動できませんでした", .zh: "已删除 — 释放 \(size)，\(n) 项无法移动", .pt: "Removido — \(size) liberados, \(n) itens não puderam ser movidos"]) }
    static var blockedByRunning: String { L("Quit the running apps first, or allow a force quit.", [.ru: "Сначала завершите запущенные приложения или разрешите принудительное завершение.", .es: "Cierra primero las apps en ejecución o permite forzar la salida.", .fr: "Quittez d’abord les apps en cours, ou autorisez la fermeture forcée.", .de: "Beende zuerst die laufenden Apps oder erlaube das sofortige Beenden.", .ja: "実行中のアプリを終了するか、強制終了を許可してください。", .zh: "请先退出运行中的应用，或允许强制退出。", .pt: "Encerre primeiro os apps em execução ou permita o encerramento forçado."]) }
    static func couldNotRemove(_ n: Int) -> String { L("\(n) items could not be removed", [.ru: "Не удалось удалить: \(n)", .es: "No se pudieron eliminar \(n) elementos", .fr: "\(n) éléments n’ont pas pu être supprimés", .de: "\(n) Objekte konnten nicht entfernt werden", .ja: "\(n) 件を削除できませんでした", .zh: "\(n) 项无法删除", .pt: "\(n) itens não puderam ser removidos"]) }
    static func failureReason(_ raw: String) -> String {
        switch raw {
        case "needsFullDiskAccess":
            return L("Helm needs Full Disk Access to move this.", [.ru: "Для перемещения нужен полный доступ к диску.", .es: "Helm necesita Acceso a disco completo para moverlo.", .fr: "Helm a besoin de l’accès complet au disque pour le déplacer.", .de: "Helm braucht vollen Festplattenzugriff dafür.", .ja: "移動にはフルディスクアクセスが必要です。", .zh: "移动此项需要完全磁盘访问权限。", .pt: "O Helm precisa de Acesso Total ao Disco para mover isto."])
        case "activeSystemExtension":
            return L("The app has an active system extension. Turn it off first.", [.ru: "У программы активно системное расширение. Сначала отключите его.", .es: "La app tiene una extensión del sistema activa. Desactívala primero.", .fr: "L’app a une extension système active. Désactivez-la d’abord.", .de: "Die App hat eine aktive Systemerweiterung. Zuerst deaktivieren.", .ja: "アプリのシステム機能拡張が有効です。先に無効にしてください。", .zh: "该应用有已启用的系统扩展，请先关闭。", .pt: "O app tem uma extensão do sistema ativa. Desative-a primeiro."])
        case "noPermission":
            return L("No permission to move this item — it may be locked or in use.", [.ru: "Нет прав на перемещение — объект может быть заблокирован или используется.", .es: "Sin permiso para mover este elemento: puede estar bloqueado o en uso.", .fr: "Pas l’autorisation de déplacer cet élément — il peut être verrouillé ou utilisé.", .de: "Keine Berechtigung zum Verschieben — möglicherweise gesperrt oder in Benutzung.", .ja: "移動する権限がありません。ロック中か使用中の可能性があります。", .zh: "没有权限移动此项——可能已锁定或正在使用。", .pt: "Sem permissão para mover este item — pode estar bloqueado ou em uso."])
        default:
            return L("macOS refused to move this item.", [.ru: "macOS отказалась перемещать этот объект.", .es: "macOS se negó a mover este elemento.", .fr: "macOS a refusé de déplacer cet élément.", .de: "macOS hat das Verschieben abgelehnt.", .ja: "macOS がこの項目の移動を拒否しました。", .zh: "macOS 拒绝移动此项。", .pt: "O macOS recusou mover este item."])
        }
    }
    static var showInFinder: String { L("Show", [.ru: "Показать", .es: "Mostrar", .fr: "Afficher", .de: "Zeigen", .ja: "表示", .zh: "显示", .pt: "Mostrar"]) }
    static var openDiskAccess: String { L("Open Full Disk Access…", [.ru: "Открыть «Доступ к диску»…", .es: "Abrir Acceso a disco…", .fr: "Ouvrir Accès complet au disque…", .de: "Vollen Festplattenzugriff öffnen…", .ja: "フルディスクアクセスを開く…", .zh: "打开完全磁盘访问…", .pt: "Abrir Acesso Total ao Disco…"]) }
    static var openExtensions: String { L("Open Extensions…", [.ru: "Открыть «Расширения»…", .es: "Abrir Extensiones…", .fr: "Ouvrir Extensions…", .de: "Erweiterungen öffnen…", .ja: "機能拡張を開く…", .zh: "打开扩展…", .pt: "Abrir Extensões…"]) }
    static var done: String { L("Done", [.ru: "Готово", .es: "Listo", .fr: "Terminé", .de: "Fertig", .ja: "完了", .zh: "完成", .pt: "Concluído"]) }
    static var refreshList: String { L("Refresh list", [.ru: "Обновить список", .es: "Actualizar lista", .fr: "Actualiser la liste", .de: "Liste aktualisieren", .ja: "リストを更新", .zh: "刷新列表", .pt: "Atualizar lista"]) }
    static func appsCount(_ n: String) -> String { L("\(n) apps", [.ru: "Приложений: \(n)", .es: "\(n) apps", .fr: "\(n) apps", .de: "\(n) Apps", .ja: "アプリ \(n) 件", .zh: "\(n) 个应用", .pt: "\(n) apps"]) }
    static func appsCountSelected(_ n: String, _ chosen: Int, _ size: String) -> String { L("\(n) apps · \(chosen) selected · \(size)", [.ru: "Приложений: \(n) · выбрано \(chosen) · \(size)", .es: "\(n) apps · \(chosen) seleccionadas · \(size)", .fr: "\(n) apps · \(chosen) sélectionnées · \(size)", .de: "\(n) Apps · \(chosen) gewählt · \(size)", .ja: "アプリ \(n) 件・選択 \(chosen)・\(size)", .zh: "\(n) 个应用 · 已选 \(chosen) · \(size)", .pt: "\(n) apps · \(chosen) selecionados · \(size)"]) }
}
