import HelmUI

enum LfStr {
    static var moduleName: String { L("System Leftovers", [.ru: "Хвосты системы", .es: "Restos del sistema", .fr: "Restes système", .de: "System-Reste", .ja: "システムの残存物", .zh: "系统残留", .pt: "Restos do sistema"]) }
    static var summary: String { L("Login items, settings and plug-ins left by apps that are gone.", [.ru: "Автозапуск, настройки и плагины, оставшиеся от удалённых программ.", .es: "Elementos de inicio, ajustes y plug-ins de apps que ya no están.", .fr: "Éléments de connexion, réglages et modules laissés par des apps disparues.", .de: "Startobjekte, Einstellungen und Plug-ins von Apps, die es nicht mehr gibt.", .ja: "削除済みアプリが残したログイン項目・設定・プラグイン。", .zh: "已删除应用遗留的登录项、设置和插件。", .pt: "Itens de início, ajustes e plug-ins deixados por apps que já se foram."]) }
    static var scan: String { L("Scan", [.ru: "Сканировать", .es: "Analizar", .fr: "Analyser", .de: "Suchen", .ja: "スキャン", .zh: "扫描", .pt: "Analisar"]) }
    static var scanning: String { L("Scanning…", [.ru: "Сканирование…", .es: "Analizando…", .fr: "Analyse…", .de: "Suche…", .ja: "スキャン中…", .zh: "扫描中…", .pt: "Analisando…"]) }
    static var rescan: String { L("Scan again", [.ru: "Сканировать заново", .es: "Analizar de nuevo", .fr: "Analyser à nouveau", .de: "Erneut suchen", .ja: "再スキャン", .zh: "重新扫描", .pt: "Analisar de novo"]) }
    static var intro: String { L("Finds launch agents, preferences and plug-ins whose app is no longer installed. Anything belonging to macOS or to an installed app is never listed.", [.ru: "Находит агенты запуска, настройки и плагины, чьи программы уже не установлены. Всё, что принадлежит macOS или установленным программам, в список не попадает.", .es: "Encuentra agentes de inicio, preferencias y plug-ins cuya app ya no está instalada. Nada de macOS ni de apps instaladas aparece aquí.", .fr: "Trouve les agents de lancement, préférences et modules dont l’app n’est plus installée. Rien appartenant à macOS ou à une app installée n’est listé.", .de: "Findet Startobjekte, Einstellungen und Plug-ins, deren App nicht mehr installiert ist. Nichts von macOS oder installierten Apps wird gelistet.", .ja: "アプリが既にインストールされていない起動エージェント・設定・プラグインを検出します。macOS やインストール済みアプリのものは一覧に含まれません。", .zh: "查找所属应用已卸载的启动代理、偏好设置和插件。属于 macOS 或已安装应用的项目不会列出。", .pt: "Encontra agentes de início, preferências e plug-ins cujo app não está mais instalado. Nada do macOS ou de apps instalados é listado."]) }
    static var notScannedYet: String { L("Scan to see what apps left behind.", [.ru: "Запустите сканирование, чтобы увидеть, что осталось от программ.", .es: "Analiza para ver qué dejaron las apps.", .fr: "Lancez une analyse pour voir ce que les apps ont laissé.", .de: "Suchen, um zu sehen, was Apps hinterlassen haben.", .ja: "スキャンして、アプリが残したものを確認します。", .zh: "扫描以查看应用留下了什么。", .pt: "Analise para ver o que os apps deixaram."]) }
    static var reviewNote: String { L("Nothing is selected by default — each of these is loaded by macOS, so pick deliberately.", [.ru: "По умолчанию ничего не выбрано: каждый из этих файлов macOS загружает, поэтому выбирайте осознанно.", .es: "Nada está seleccionado por defecto: macOS carga cada uno de estos archivos, elige con cuidado.", .fr: "Rien n’est sélectionné par défaut : macOS charge chacun de ces fichiers, choisissez délibérément.", .de: "Nichts ist vorausgewählt — macOS lädt jede dieser Dateien, also bewusst auswählen.", .ja: "既定では何も選択されていません。これらは macOS が読み込むファイルです。慎重に選んでください。", .zh: "默认不选中任何项——这些文件由 macOS 加载，请谨慎选择。", .pt: "Nada é selecionado por padrão — o macOS carrega cada um destes arquivos, escolha com atenção."]) }
    static var nothingFound: String { L("Nothing left behind.", [.ru: "Хвостов не найдено.", .es: "No quedó nada.", .fr: "Rien n’a été laissé.", .de: "Nichts übrig geblieben.", .ja: "残存物はありません。", .zh: "没有残留。", .pt: "Nada ficou para trás."]) }
    static var removeSelected: String { L("Move to Trash", [.ru: "Переместить в Корзину", .es: "Mover a la Papelera", .fr: "Placer dans la corbeille", .de: "In den Papierkorb", .ja: "ゴミ箱に入れる", .zh: "移到废纸篓", .pt: "Mover para o Lixo"]) }
    static var selectAll: String { L("Select all", [.ru: "Выбрать все", .es: "Seleccionar todo", .fr: "Tout sélectionner", .de: "Alle auswählen", .ja: "すべて選択", .zh: "全选", .pt: "Selecionar tudo"]) }
    static var deselectAll: String { L("Clear selection", [.ru: "Снять выбор", .es: "Quitar selección", .fr: "Tout désélectionner", .de: "Auswahl aufheben", .ja: "選択を解除", .zh: "取消选择", .pt: "Limpar seleção"]) }
    static var runsAtLogin: String { L("Runs at login", [.ru: "Запускается при входе", .es: "Se ejecuta al iniciar sesión", .fr: "S’exécute à la connexion", .de: "Startet bei der Anmeldung", .ja: "ログイン時に実行", .zh: "登录时运行", .pt: "Executa ao iniciar sessão"]) }
    static func missingTarget(_ path: String) -> String { L("Points at a missing file: \(path)", [.ru: "Ссылается на отсутствующий файл: \(path)", .es: "Apunta a un archivo inexistente: \(path)", .fr: "Pointe vers un fichier absent : \(path)", .de: "Verweist auf eine fehlende Datei: \(path)", .ja: "存在しないファイルを参照: \(path)", .zh: "指向缺失的文件：\(path)", .pt: "Aponta para um arquivo ausente: \(path)"]) }
    static func foundCount(_ n: Int, _ size: String) -> String { L("\(n) items · \(size)", [.ru: "Объектов: \(n) · \(size)", .es: "\(n) elementos · \(size)", .fr: "\(n) éléments · \(size)", .de: "\(n) Objekte · \(size)", .ja: "\(n) 件・\(size)", .zh: "\(n) 项 · \(size)", .pt: "\(n) itens · \(size)"]) }
    static func removedFreed(_ size: String) -> String { L("Removed — \(size) freed", [.ru: "Удалено — освобождено \(size)", .es: "Eliminado — \(size) liberados", .fr: "Supprimé — \(size) libérés", .de: "Entfernt — \(size) frei", .ja: "削除しました — \(size) を解放", .zh: "已删除 — 释放 \(size)", .pt: "Removido — \(size) liberados"]) }
    static func kindName(_ kind: String) -> String {
        switch kind {
        case "launchAgent": return L("Launch agents", [.ru: "Агенты запуска", .es: "Agentes de inicio", .fr: "Agents de lancement", .de: "Startobjekte", .ja: "起動エージェント", .zh: "启动代理", .pt: "Agentes de início"])
        case "launchDaemon": return L("Launch daemons", [.ru: "Демоны запуска", .es: "Demonios de inicio", .fr: "Démons de lancement", .de: "Start-Daemons", .ja: "起動デーモン", .zh: "启动守护进程", .pt: "Daemons de início"])
        case "preference": return L("Settings files", [.ru: "Файлы настроек", .es: "Archivos de ajustes", .fr: "Fichiers de réglages", .de: "Einstellungsdateien", .ja: "設定ファイル", .zh: "设置文件", .pt: "Arquivos de ajustes"])
        case "systemExtension": return L("System extensions", [.ru: "Системные расширения", .es: "Extensiones del sistema", .fr: "Extensions système", .de: "Systemerweiterungen", .ja: "システム機能拡張", .zh: "系统扩展", .pt: "Extensões do sistema"])
        default: return L("Plug-ins", [.ru: "Плагины", .es: "Plug-ins", .fr: "Modules", .de: "Plug-ins", .ja: "プラグイン", .zh: "插件", .pt: "Plug-ins"])
        }
    }
}
