import HelmUI

enum IsStr {
    static var moduleName: String { L("Island", [.ru: "Остров", .es: "Isla", .fr: "Îlot", .de: "Island", .ja: "アイランド", .zh: "灵动岛", .pt: "Ilha"]) }
    static var summary: String { L("A Dynamic Island around the notch.", [.ru: "Dynamic Island вокруг ноутча.", .es: "Una Dynamic Island alrededor del notch.", .fr: "Une Dynamic Island autour de l’encoche.", .de: "Eine Dynamic Island um den Notch.", .ja: "ノッチまわりの Dynamic Island。", .zh: "围绕刘海的灵动岛。", .pt: "Uma Dynamic Island ao redor do notch."]) }
    static var dropHint: String { L("Drop files here", [.ru: "Бросьте файлы сюда", .es: "Suelta archivos aquí", .fr: "Déposez des fichiers ici", .de: "Dateien hier ablegen", .ja: "ここにファイルをドロップ", .zh: "把文件拖到这里", .pt: "Solte arquivos aqui"]) }
    static func itemCount(_ n: Int) -> String { L("\(n) on the shelf", [.ru: "На полке: \(n)", .es: "\(n) en el estante", .fr: "\(n) sur l’étagère", .de: "\(n) auf der Ablage", .ja: "シェルフに \(n) 件", .zh: "架上 \(n) 项", .pt: "\(n) na prateleira"]) }
    static var clear: String { L("Clear", [.ru: "Очистить", .es: "Vaciar", .fr: "Vider", .de: "Leeren", .ja: "クリア", .zh: "清空", .pt: "Limpar"]) }
    static var remove: String { L("Remove", [.ru: "Убрать", .es: "Quitar", .fr: "Retirer", .de: "Entfernen", .ja: "削除", .zh: "移除", .pt: "Remover"]) }
    static var revealInFinder: String { L("Reveal in Finder", [.ru: "Показать в Finder", .es: "Mostrar en Finder", .fr: "Afficher dans le Finder", .de: "Im Finder zeigen", .ja: "Finder に表示", .zh: "在访达中显示", .pt: "Mostrar no Finder"]) }
    static var behavior: String { L("Behavior", [.ru: "Поведение", .es: "Comportamiento", .fr: "Comportement", .de: "Verhalten", .ja: "動作", .zh: "行为", .pt: "Comportamento"]) }
    static var hoverToOpen: String { L("Open on hover over the notch", [.ru: "Открывать при наведении на ноутч", .es: "Abrir al pasar el cursor por el notch", .fr: "Ouvrir au survol de l’encoche", .de: "Beim Überfahren des Notch öffnen", .ja: "ノッチにポインタを合わせて開く", .zh: "指针悬停刘海时打开", .pt: "Abrir ao passar o cursor no notch"]) }
    static var revealOnDrag: String { L("Reveal when a file drag starts", [.ru: "Показывать при начале переноса файла", .es: "Mostrar al empezar a arrastrar un archivo", .fr: "Afficher dès qu’un glisser de fichier commence", .de: "Beim Start eines Datei-Drags zeigen", .ja: "ファイルのドラッグ開始時に表示", .zh: "开始拖动文件时显示", .pt: "Mostrar quando um arraste de arquivo começar"]) }
    static var revealOnDragNote: String { L("Drop onto the card below the menu bar — no need to hover at the top edge, so Mission Control stays out of the way.", [.ru: "Бросайте на карточку под строкой меню — у верхней кромки задерживаться не нужно, Mission Control не мешает.", .es: "Suelta sobre la tarjeta bajo la barra de menús; no hace falta quedarse en el borde superior.", .fr: "Déposez sur la carte sous la barre des menus — inutile de rester au bord supérieur.", .de: "Auf der Karte unter der Menüleiste ablegen — kein Verweilen an der Oberkante nötig.", .ja: "メニューバー下のカードにドロップ。上端で待つ必要はありません。", .zh: "放到菜单栏下方的卡片上——无需停留在屏幕上缘。", .pt: "Solte no cartão abaixo da barra de menus — sem esperar na borda superior."]) }
    static var systemEvents: String { L("Show power events", [.ru: "Показывать события питания", .es: "Mostrar eventos de energía", .fr: "Afficher les événements d’alimentation", .de: "Energie-Ereignisse anzeigen", .ja: "電源イベントを表示", .zh: "显示电源事件", .pt: "Mostrar eventos de energia"]) }
    static var noNotch: String { L("This Mac has no notch — the island is unavailable.", [.ru: "У этого Mac нет ноутча — остров недоступен.", .es: "Este Mac no tiene notch: la isla no está disponible.", .fr: "Ce Mac n’a pas d’encoche — l’îlot est indisponible.", .de: "Dieser Mac hat keinen Notch — die Island ist nicht verfügbar.", .ja: "この Mac にはノッチがないため、アイランドは利用できません。", .zh: "这台 Mac 没有刘海，无法使用灵动岛。", .pt: "Este Mac não tem notch — a ilha não está disponível."]) }
    static var eventsSection: String { L("Events", [.ru: "События", .es: "Eventos", .fr: "Événements", .de: "Ereignisse", .ja: "イベント", .zh: "事件", .pt: "Eventos"]) }
    static var audioEvents: String { L("Show volume and audio devices", [.ru: "Показывать громкость и аудиоустройства", .es: "Mostrar volumen y dispositivos de audio", .fr: "Afficher le volume et les périphériques audio", .de: "Lautstärke und Audiogeräte anzeigen", .ja: "音量とオーディオデバイスを表示", .zh: "显示音量和音频设备", .pt: "Mostrar volume e dispositivos de áudio"]) }
    static var mediaEvents: String { L("Show now playing (Music, Spotify)", [.ru: "Показывать «Сейчас играет» (Music, Spotify)", .es: "Mostrar «Ahora suena» (Music, Spotify)", .fr: "Afficher « En lecture » (Music, Spotify)", .de: "„Läuft gerade“ anzeigen (Music, Spotify)", .ja: "再生中を表示（Music、Spotify）", .zh: "显示正在播放（Music、Spotify）", .pt: "Mostrar «Tocando agora» (Music, Spotify)"]) }
    static var replaceHUD: String { L("Replace the system volume indicator", [.ru: "Заменять системный индикатор громкости", .es: "Sustituir el indicador de volumen del sistema", .fr: "Remplacer l’indicateur de volume du système", .de: "Systemlautstärke-Anzeige ersetzen", .ja: "システムの音量インジケータを置き換える", .zh: "替换系统音量指示器", .pt: "Substituir o indicador de volume do sistema"]) }
    static var replaceHUDNote: String { L("The volume keys drive the island instead of the macOS overlay. Requires Accessibility access.", [.ru: "Клавиши громкости управляют островом вместо оверлея macOS. Требуется доступ «Универсальный доступ».", .es: "Las teclas de volumen controlan la isla en lugar del panel de macOS. Requiere acceso de Accesibilidad.", .fr: "Les touches de volume pilotent l’îlot au lieu de l’overlay macOS. Nécessite l’accès Accessibilité.", .de: "Die Lautstärketasten steuern die Island statt des macOS-Overlays. Erfordert Bedienungshilfen-Zugriff.", .ja: "音量キーが macOS のオーバーレイの代わりにアイランドを操作します。アクセシビリティ権限が必要です。", .zh: "音量键将控制灵动岛而非 macOS 悬浮层。需要辅助功能权限。", .pt: "As teclas de volume controlam a ilha em vez do overlay do macOS. Requer acesso de Acessibilidade."]) }
    static var notPlaying: String { L("Nothing playing", [.ru: "Ничего не играет", .es: "No suena nada", .fr: "Rien en lecture", .de: "Nichts läuft", .ja: "再生中の曲はありません", .zh: "没有在播放", .pt: "Nada tocando"]) }
    static var charging: String { L("Charging", [.ru: "Заряжается", .es: "Cargando", .fr: "En charge", .de: "Lädt", .ja: "充電中", .zh: "充电中", .pt: "Carregando"]) }
    static var onBattery: String { L("On battery", [.ru: "От батареи", .es: "Con batería", .fr: "Sur batterie", .de: "Auf Batterie", .ja: "バッテリー駆動", .zh: "使用电池", .pt: "Na bateria"]) }
}
