import SwiftUI
import HelmUI

/// The in-app changelog: structured and localized through the same `L()` tables
/// as the rest of the UI, so "What's New" reads in the user's language. The
/// repo's CHANGELOG.md stays the canonical English record for GitHub.
enum ChangeKind {
    case new, upd, fix

    var label: String {
        switch self {
        case .new: return "New"
        case .upd: return "Upd"
        case .fix: return "Fix"
        }
    }

    var color: Color {
        switch self {
        case .new: return .green
        case .upd: return .blue
        case .fix: return .orange
        }
    }
}

struct ChangeItem: Identifiable {
    let id = UUID()
    let kind: ChangeKind
    let text: String
}

struct ChangelogEntry: Identifiable {
    var id: String { version }
    let version: String
    let date: String
    let items: [ChangeItem]
}

enum Changelog {
    /// Computed so `L()` resolves against the current language each time.
    static var entries: [ChangelogEntry] {
        [
            ChangelogEntry(version: "0.7.0-dev.4", date: "2026-07-25", items: [
                ChangeItem(kind: .upd, text: L("Settings opens at a width sized against the densest page, with a floor below which rows would start truncating.", [.ru: "Окно настроек открывается с шириной, подобранной по самой плотной странице, и не сжимается до размера, где строки начинают обрезаться.", .es: "Ajustes abre con un ancho ajustado a la página más densa y no se puede reducir hasta truncar filas.", .fr: "Les Réglages s’ouvrent à une largeur calée sur la page la plus dense, avec un minimum sous lequel les lignes seraient tronquées.", .de: "Die Einstellungen öffnen in einer Breite, die an der dichtesten Seite bemessen ist, mit einer Untergrenze gegen abgeschnittene Zeilen.", .ja: "設定は最も情報量の多い画面に合わせた幅で開き、行が切れる幅より狭くはできません。", .zh: "设置窗口以最密集页面为准的宽度打开，且不能缩到会截断行的宽度以下。", .pt: "Ajustes abre com largura dimensionada pela página mais densa e não encolhe até truncar linhas."])),
                ChangeItem(kind: .fix, text: L("Homebrew shows a spinner while the first package list loads instead of saying nothing is installed.", [.ru: "Homebrew показывает индикатор загрузки первого списка пакетов вместо «нет установленных пакетов».", .es: "Homebrew muestra un indicador mientras carga la primera lista en vez de decir que no hay paquetes.", .fr: "Homebrew affiche un indicateur pendant le premier chargement au lieu d’annoncer qu’il n’y a rien.", .de: "Homebrew zeigt beim ersten Laden einen Ladeindikator statt „nichts installiert“.", .ja: "Homebrew は最初のリスト読み込み中に「未インストール」ではなくインジケータを表示します。", .zh: "Homebrew 在首次加载列表时显示进度指示，而不是提示未安装任何包。", .pt: "O Homebrew mostra um indicador enquanto a primeira lista carrega, em vez de dizer que não há pacotes."])),
            ]),
            ChangelogEntry(version: "0.7.0-dev.3", date: "2026-07-25", items: [
                ChangeItem(kind: .fix, text: L("The Helm mark now contrasts with the window: dark in light mode, light in dark mode. Settings keeps one window size, uninstaller checkboxes line up, the instrument strip floats on a system material, and Homebrew rows no longer jump while descriptions load.", [.ru: "Знак Helm теперь контрастен окну: тёмный в светлой теме, светлый в тёмной. Окно настроек не меняет размер, чекбоксы в удалении выровнены, приборная строка — на системном материале с отступами, а список Homebrew больше не прыгает при загрузке описаний.", .es: "La marca de Helm ahora contrasta con la ventana: oscura en modo claro, clara en modo oscuro. Ajustes mantiene un tamaño, las casillas se alinean, la tira de indicadores flota sobre material del sistema y las filas de Homebrew ya no saltan.", .fr: "La marque Helm contraste avec la fenêtre : sombre en clair, claire en sombre. Les Réglages gardent une taille, les cases sont alignées, la barre d’indicateurs flotte sur un matériau système et les lignes Homebrew ne sautent plus.", .de: "Die Helm-Marke kontrastiert jetzt mit dem Fenster: dunkel im hellen Modus, hell im dunklen. Einstellungen behalten eine Größe, Kontrollkästchen sind ausgerichtet, die Instrumentenleiste schwebt auf Systemmaterial, Homebrew-Zeilen springen nicht mehr.", .ja: "Helm のマークがウインドウと反転：ライトでは暗く、ダークでは明るく。設定のサイズは一定に、チェックボックスは整列、計器バーはシステムマテリアル上に浮き、Homebrew の行は説明読み込み中も揺れません。", .zh: "Helm 标记与窗口反差：浅色模式为深色，深色模式为浅色。设置窗口尺寸固定，复选框对齐，仪表条浮于系统材质之上，Homebrew 列表加载描述时不再跳动。", .pt: "A marca do Helm agora contrasta com a janela: escura no modo claro, clara no escuro. Ajustes mantém um tamanho, as caixas ficam alinhadas, a faixa de indicadores flutua sobre material do sistema e as linhas do Homebrew não saltam mais."])),
            ]),
            ChangelogEntry(version: "0.7.0-dev.2", date: "2026-07-25", items: [
                ChangeItem(kind: .new, text: L("App Uninstaller now works in two steps: tick the apps, then review the files found for each of them. Running apps are flagged and only removed if you allow a force quit.", [.ru: "Удаление приложений теперь в два шага: отметьте программы, затем разберите найденные файлы по каждой. Запущенные помечаются и удаляются только если разрешить принудительное завершение.", .es: "El Desinstalador ahora funciona en dos pasos: marca las apps y luego revisa los archivos de cada una. Las apps en ejecución se señalan y solo se eliminan si permites forzar la salida.", .fr: "La désinstallation se fait en deux étapes : cochez les apps, puis vérifiez les fichiers trouvés pour chacune. Les apps en cours sont signalées et supprimées seulement si vous autorisez la fermeture forcée.", .de: "Die Deinstallation läuft jetzt in zwei Schritten: Apps ankreuzen, dann die gefundenen Dateien je App prüfen. Laufende Apps werden markiert und nur nach erlaubtem Sofort-Beenden entfernt.", .ja: "アンインストールは2ステップに：アプリを選び、次にアプリごとに見つかったファイルを確認します。実行中のアプリは印が付き、強制終了を許可した場合のみ削除されます。", .zh: "应用卸载改为两步：先勾选应用，再逐个查看找到的文件。运行中的应用会被标记，只有允许强制退出才会删除。", .pt: "A desinstalação agora tem dois passos: marque os apps e depois revise os arquivos encontrados de cada um. Apps em execução são sinalizados e só removidos se você permitir o encerramento forçado."])),
                ChangeItem(kind: .new, text: L("Diagnostics log: dev builds always record what Helm does, and Settings → Diagnostics can show, copy or clear the file.", [.ru: "Журнал диагностики: dev-сборки всегда записывают действия Helm, а в «Настройки → Диагностика» его можно показать, скопировать или очистить.", .es: "Registro de diagnóstico: las compilaciones dev siempre anotan lo que hace Helm; en Ajustes → Diagnóstico puedes verlo, copiarlo o borrarlo.", .fr: "Journal de diagnostic : les versions dev enregistrent toujours ce que fait Helm ; Réglages → Diagnostic permet de l’afficher, le copier ou l’effacer.", .de: "Diagnose-Protokoll: Dev-Builds zeichnen immer auf, was Helm tut; unter Einstellungen → Diagnose lässt es sich zeigen, kopieren oder leeren.", .ja: "診断ログ：dev ビルドは常に動作を記録し、「設定 → 診断」で表示・コピー・消去できます。", .zh: "诊断日志：开发版始终记录 Helm 的操作，可在“设置 → 诊断”查看、复制或清空。", .pt: "Registro de diagnóstico: builds dev sempre gravam o que o Helm faz, e em Ajustes → Diagnóstico dá para ver, copiar ou limpar."])),
                ChangeItem(kind: .upd, text: L("Every screen now follows the About page: a glowing icon plate in the header and instrument-style figures for the numbers that matter there.", [.ru: "Все экраны приведены к виду окна «О Helm»: иконка со свечением в шапке и приборные показания для важных чисел.", .es: "Todas las pantallas siguen ahora a Acerca de: placa de icono con brillo en la cabecera y cifras tipo instrumento.", .fr: "Tous les écrans suivent désormais À propos : plaque d’icône lumineuse en en-tête et chiffres façon instruments.", .de: "Alle Bildschirme folgen jetzt der Über-Seite: leuchtende Symbolplatte im Kopf und Instrumentenanzeigen für die wichtigen Zahlen.", .ja: "すべての画面が「Helm について」の様式に：ヘッダーに光るアイコン、重要な数値は計器風表示。", .zh: "所有界面统一为“关于”页的风格：标题处发光图标，关键数字以仪表样式呈现。", .pt: "Todas as telas seguem a página Sobre: placa de ícone com brilho no cabeçalho e números em estilo de instrumento."])),
            ]),
            ChangelogEntry(version: "0.6.3", date: "2026-07-25", items: [
                ChangeItem(kind: .upd, text: L("Redesigned About: the icon sits in a bezel that turns while updates are checked, version and build read as instrument dials, and update controls live in one card.", [.ru: "Новое окно «О Helm»: иконка в безеле, который вращается во время проверки обновлений, версия и сборка — как показания приборов, управление обновлениями собрано в одну карточку.", .es: "Ventana Acerca de renovada: el icono en un bisel que gira mientras se buscan actualizaciones, versión y compilación como diales, y los controles de actualización en una sola tarjeta.", .fr: "Fenêtre À propos repensée : l’icône dans un cerclage qui tourne pendant la recherche de mises à jour, version et build en cadrans, et les commandes de mise à jour réunies dans une carte.", .de: "Neu gestaltetes Über-Fenster: das Symbol in einer Lünette, die sich während der Update-Prüfung dreht, Version und Build als Instrumentenanzeige, Update-Steuerung in einer Karte.", .ja: "「Helm について」を刷新：アップデート確認中に回転するベゼル内のアイコン、計器のようなバージョンとビルド表示、更新操作を1枚のカードに集約。", .zh: "重新设计“关于”：图标置于检查更新时旋转的表圈中，版本与构建如仪表读数，更新控件集中在一张卡片。", .pt: "Janela Sobre redesenhada: o ícone num aro que gira durante a verificação de atualizações, versão e build como mostradores, e os controles de atualização em um único cartão."])),
                ChangeItem(kind: .fix, text: L("The update status no longer claims you are current when no check has run — it shows when the last check happened.", [.ru: "Статус обновлений больше не утверждает, что версия последняя, если проверки не было — показывает, когда проверяли в последний раз.", .es: "El estado de actualización ya no afirma que estás al día sin haber comprobado: muestra cuándo fue la última comprobación.", .fr: "L’état des mises à jour n’affirme plus que vous êtes à jour sans vérification : il indique la dernière vérification.", .de: "Der Update-Status behauptet nicht mehr, aktuell zu sein, ohne geprüft zu haben — er zeigt die letzte Prüfung.", .ja: "未確認のまま「最新です」と表示せず、最後に確認した時刻を表示します。", .zh: "未执行检查时不再声称已是最新，而是显示上次检查时间。", .pt: "O status de atualização não afirma mais que você está atualizado sem ter verificado — mostra a última verificação."])),
            ]),
            ChangelogEntry(version: "0.6.2", date: "2026-07-25", items: [
                ChangeItem(kind: .new, text: L("Update channels: stay on finished releases, or switch to Dev in About to get early builds.", [.ru: "Каналы обновлений: оставайтесь на законченных релизах или переключитесь на Dev в «О Helm», чтобы получать ранние сборки.", .es: "Canales de actualización: quédate en versiones finales o cambia a Dev en Acerca de para recibir compilaciones tempranas.", .fr: "Canaux de mise à jour : restez sur les versions finalisées ou passez au canal Dev dans À propos pour les versions précoces.", .de: "Update-Kanäle: bei fertigen Releases bleiben oder in Über auf Dev wechseln, um frühe Builds zu erhalten.", .ja: "アップデートチャンネル：完成版のままにするか、「Helm について」で Dev に切り替えて早期ビルドを受け取れます。", .zh: "更新通道：可停留在正式版本，或在“关于”中切换到 Dev 获取早期构建。", .pt: "Canais de atualização: fique nas versões finalizadas ou mude para Dev em Sobre para receber builds iniciais."])),
            ]),
            ChangelogEntry(version: "0.6.1", date: "2026-07-25", items: [
                ChangeItem(kind: .fix, text: L("VPN rows no longer show an endless spinner: the status is re-checked until the connection settles.", [.ru: "Строки VPN больше не показывают вечный спиннер: статус перепроверяется, пока подключение не устаканится.", .es: "Las filas de VPN ya no muestran un indicador infinito: el estado se vuelve a comprobar hasta que la conexión se estabiliza.", .fr: "Les lignes VPN n’affichent plus d’indicateur sans fin : l’état est revérifié jusqu’à stabilisation de la connexion.", .de: "VPN-Zeilen zeigen keinen endlosen Spinner mehr: der Status wird neu geprüft, bis die Verbindung steht.", .ja: "VPN の行でスピナーが回り続けなくなりました。接続が安定するまで状態を再確認します。", .zh: "VPN 行不再无限转圈：状态会持续复查直到连接稳定。", .pt: "As linhas de VPN não mostram mais um indicador infinito: o estado é verificado novamente até a conexão estabilizar."])),
            ]),
            ChangelogEntry(version: "0.6.0", date: "2026-07-25", items: [
                ChangeItem(kind: .new, text: L("App Uninstaller module: remove apps together with their caches, settings and other leftovers; find leftovers of apps that are already gone.", [.ru: "Модуль «Удаление приложений»: удаление вместе с кешами, настройками и другими хвостами; поиск остатков уже удалённых программ.", .es: "Módulo Desinstalador: elimina apps junto con sus cachés, ajustes y otros restos; encuentra restos de apps ya eliminadas.", .fr: "Module Désinstallation : supprime les apps avec leurs caches, réglages et autres restes ; retrouve les restes d’apps déjà supprimées.", .de: "Deinstallations-Modul: entfernt Apps samt Caches, Einstellungen und anderen Resten; findet Reste bereits gelöschter Apps.", .ja: "アンインストールモジュール：キャッシュや設定などの残存ファイルごとアプリを削除。削除済みアプリの残存ファイルも検索。", .zh: "应用卸载模块：连同缓存、设置等残留一并删除；还可查找已删除应用的残留。", .pt: "Módulo Desinstalador: remove apps junto com caches, ajustes e outros restos; encontra restos de apps já removidos."])),
                ChangeItem(kind: .new, text: L("Homebrew module: installed packages, updates, search and install, with a live console and package descriptions.", [.ru: "Модуль Homebrew: установленные пакеты, обновления, поиск и установка, живая консоль и описания пакетов.", .es: "Módulo Homebrew: paquetes instalados, actualizaciones, búsqueda e instalación, con consola en vivo y descripciones.", .fr: "Module Homebrew : paquets installés, mises à jour, recherche et installation, avec console en direct et descriptions.", .de: "Homebrew-Modul: installierte Pakete, Updates, Suche und Installation, mit Live-Konsole und Paketbeschreibungen.", .ja: "Homebrew モジュール：インストール済みパッケージ、アップデート、検索とインストール。ライブコンソールと説明付き。", .zh: "Homebrew 模块：已安装包、更新、搜索与安装，带实时控制台和包描述。", .pt: "Módulo Homebrew: pacotes instalados, atualizações, busca e instalação, com console ao vivo e descrições."])),
                ChangeItem(kind: .new, text: L("Menu-bar timer: the ring empties clockwise while a timer runs, with optional remaining time and its own colour.", [.ru: "Таймер в строке меню: кольцо убывает по часовой, опционально время и свой цвет.", .es: "Temporizador en la barra: el anillo se vacía en sentido horario, con tiempo restante y color propio opcionales.", .fr: "Minuteur dans la barre : l’anneau se vide dans le sens horaire, temps restant et couleur dédiée en option.", .de: "Menüleisten-Timer: der Ring leert sich im Uhrzeigersinn, optional mit Restzeit und eigener Farbe.", .ja: "メニューバーのタイマー：リングが時計回りに減少。残り時間表示と専用カラーも選択可。", .zh: "菜单栏计时：圆环顺时针递减，可选剩余时间与专属颜色。", .pt: "Timer na barra: o anel se esvazia no sentido horário, com tempo restante e cor própria opcionais."])),
                ChangeItem(kind: .new, text: L("Utilities live in a collapsible panel section; optional Settings and Quit buttons; the right-click menu jumps straight to any module.", [.ru: "Утилиты — в раскрывающейся секции панели; опциональные кнопки «Настройки» и «Выйти»; меню правого клика ведёт сразу в модуль.", .es: "Las utilidades viven en una sección plegable del panel; botones opcionales de Ajustes y Salir; el menú contextual salta directo a un módulo.", .fr: "Les utilitaires vivent dans une section repliable ; boutons Réglages et Quitter en option ; le menu contextuel ouvre directement un module.", .de: "Dienstprogramme in einer aufklappbaren Panel-Sektion; optionale Einstellungen/Beenden-Tasten; das Rechtsklickmenü springt direkt zum Modul.", .ja: "ユーティリティはパネルの折りたたみセクションに。設定/終了ボタンを追加可能。右クリックメニューから各モジュールへ直行。", .zh: "实用工具收纳于面板可折叠区；可选“设置/退出”按钮；右键菜单直达任意模块。", .pt: "Utilitários em seção recolhível do painel; botões opcionais Ajustes e Sair; o menu de contexto abre direto um módulo."])),
                ChangeItem(kind: .upd, text: L("Keep Awake's ⋯ controls open inline with animation: custom timer with a durations menu, automation toggles, Stop button in the countdown.", [.ru: "Блок «⋯» открывается прямо в карточке с анимацией: свой таймер с меню длительностей, тумблеры автоматизации, «Стоп» в отсчёте.", .es: "Los controles ⋯ se abren en línea con animación: temporizador propio con menú de duraciones, automatización y botón Detener.", .fr: "Les contrôles ⋯ s’ouvrent en ligne avec animation : minuteur personnalisé avec menu de durées, automatisations, bouton Arrêter.", .de: "Die ⋯-Steuerung öffnet inline mit Animation: eigener Timer mit Dauer-Menü, Automatik-Schalter, Stopp-Taste im Countdown.", .ja: "⋯ の操作はカード内でアニメーション表示：時間メニュー付きカスタムタイマー、自動化スイッチ、停止ボタン。", .zh: "⋯ 控件在卡片内动画展开：自定义计时（时长菜单）、自动化开关、倒计时中的停止按钮。", .pt: "Os controles ⋯ abrem na própria carta com animação: timer com menu de durações, automações e botão Parar."])),
                ChangeItem(kind: .upd, text: L("Settings window polish: larger window for utility pages, macOS 26-style lists, clearer wording throughout.", [.ru: "Полировка окна настроек: увеличенное окно для утилит, списки в стиле macOS 26, выверенные тексты.", .es: "Pulido de Ajustes: ventana mayor para utilidades, listas al estilo macOS 26, textos más claros.", .fr: "Réglages peaufinés : fenêtre agrandie pour les utilitaires, listes façon macOS 26, textes clarifiés.", .de: "Einstellungen poliert: größeres Fenster für Dienstprogramme, Listen im macOS-26-Stil, klarere Texte.", .ja: "設定ウインドウを改良：ユーティリティは大きめのウインドウ、macOS 26 スタイルのリスト、文言を整理。", .zh: "设置窗口打磨：实用工具使用更大窗口、macOS 26 风格列表、更清晰的文案。", .pt: "Ajustes refinados: janela maior para utilitários, listas no estilo macOS 26, textos mais claros."])),
                ChangeItem(kind: .fix, text: L("The panel no longer jumps or slides when sections expand; settings stay in sync between the panel and the Settings window.", [.ru: "Панель больше не прыгает при раскрытии секций; настройки синхронизированы между панелью и окном настроек.", .es: "El panel ya no salta al expandir secciones; los ajustes se sincronizan entre panel y ventana.", .fr: "Le panneau ne saute plus à l’ouverture des sections ; les réglages restent synchronisés entre panneau et fenêtre.", .de: "Das Panel springt beim Aufklappen nicht mehr; Einstellungen bleiben zwischen Panel und Fenster synchron.", .ja: "セクション展開時にパネルが跳ねなくなり、パネルと設定ウインドウの設定が同期されます。", .zh: "展开区块时面板不再跳动；面板与设置窗口的设置保持同步。", .pt: "O painel não pula mais ao expandir seções; os ajustes ficam sincronizados entre painel e janela."])),
                ChangeItem(kind: .fix, text: L("The menu-bar countdown ticks reliably; heavy work no longer stalls the app's async machinery.", [.ru: "Отсчёт в строке меню тикает стабильно; тяжёлые операции больше не тормозят асинхронику приложения.", .es: "La cuenta atrás avanza de forma fiable; el trabajo pesado ya no atasca la maquinaria asíncrona.", .fr: "Le compte à rebours avance de façon fiable ; les tâches lourdes ne bloquent plus l’asynchrone.", .de: "Der Countdown tickt zuverlässig; schwere Arbeit bremst die Async-Maschinerie nicht mehr.", .ja: "メニューバーのカウントダウンが確実に進み、重い処理が非同期機構を塞がなくなりました。", .zh: "菜单栏倒计时稳定走动；繁重任务不再阻塞异步机制。", .pt: "A contagem na barra avança de forma confiável; trabalho pesado não trava mais a máquina assíncrona."])),
            ]),
            ChangelogEntry(version: "0.5.1", date: "2026-07-24", items: [
                ChangeItem(kind: .fix, text: L("Silent update cleans up its temporary files after installing.", [.ru: "Тихое обновление подчищает временные файлы после установки.", .es: "La actualización silenciosa limpia sus archivos temporales tras instalar.", .fr: "La mise à jour silencieuse nettoie ses fichiers temporaires après installation.", .de: "Das stille Update räumt seine temporären Dateien nach der Installation auf.", .ja: "サイレントアップデートがインストール後に一時ファイルを削除します。", .zh: "静默更新安装后清理临时文件。", .pt: "A atualização silenciosa limpa os arquivos temporários após instalar."])),
            ]),
            ChangelogEntry(version: "0.5.0", date: "2026-07-24", items: [
                ChangeItem(kind: .new, text: L("Silent in-app updates: Update & Relaunch downloads, installs and restarts with no Gatekeeper prompt.", [.ru: "Тихие обновления: «Обновить и перезапустить» скачивает, ставит и перезапускает без запросов Gatekeeper.", .es: "Actualizaciones silenciosas: Actualizar y reiniciar descarga, instala y reinicia sin avisos de Gatekeeper.", .fr: "Mises à jour silencieuses : Mettre à jour et relancer télécharge, installe et redémarre sans invite Gatekeeper.", .de: "Stille Updates: Aktualisieren & neu starten lädt, installiert und startet neu ohne Gatekeeper-Abfrage.", .ja: "サイレント更新：「更新して再起動」がダウンロード・インストール・再起動まで自動で行います。", .zh: "静默更新：“更新并重启”自动下载、安装并重启，无 Gatekeeper 提示。", .pt: "Atualizações silenciosas: Atualizar e reiniciar baixa, instala e reinicia sem avisos do Gatekeeper."])),
            ]),
            ChangelogEntry(version: "0.4.0", date: "2026-07-24", items: [
                ChangeItem(kind: .new, text: L("Custom active-state icon for Keep Awake.", [.ru: "Своя иконка активного состояния для «Не спать».", .es: "Icono activo personalizado para Mantener activo.", .fr: "Icône active personnalisée pour Rester éveillé.", .de: "Eigenes Aktiv-Symbol für Wach halten.", .ja: "スリープ防止のカスタムアクティブアイコン。", .zh: "保持唤醒的自定义激活图标。", .pt: "Ícone ativo personalizado para Manter ativo."])),
                ChangeItem(kind: .upd, text: L("Reworked icon pickers with real-size previews; smaller icon sizes.", [.ru: "Переработанные пикеры иконки с превью в реальном размере; меньшие размеры.", .es: "Selectores de icono renovados con vistas a tamaño real; tamaños más pequeños.", .fr: "Sélecteurs d’icône repensés avec aperçus à taille réelle ; tailles plus petites.", .de: "Überarbeitete Symbol-Auswahl mit Vorschau in Originalgröße; kleinere Größen.", .ja: "実寸プレビュー付きの新しいアイコンピッカー。より小さいサイズも追加。", .zh: "重做的图标选择器（实际尺寸预览）；新增更小尺寸。", .pt: "Seletores de ícone renovados com prévia em tamanho real; tamanhos menores."])),
            ]),
            ChangelogEntry(version: "0.3.0", date: "2026-07-24", items: [
                ChangeItem(kind: .upd, text: L("Update check moved into About.", [.ru: "Проверка обновлений переехала в «О Helm».", .es: "La comprobación de actualizaciones se movió a Acerca de.", .fr: "La vérification des mises à jour a déménagé dans À propos.", .de: "Die Update-Prüfung ist nach Über umgezogen.", .ja: "アップデート確認を「Helm について」に移動。", .zh: "更新检查移至“关于”。", .pt: "A verificação de atualizações foi para Sobre."])),
                ChangeItem(kind: .fix, text: L("Panel toggles show the real state right after launch.", [.ru: "Тумблеры панели показывают реальное состояние сразу после запуска.", .es: "Los interruptores del panel muestran el estado real justo tras el arranque.", .fr: "Les interrupteurs du panneau montrent l’état réel dès le lancement.", .de: "Panel-Schalter zeigen direkt nach dem Start den echten Zustand.", .ja: "起動直後からパネルのスイッチが実際の状態を表示。", .zh: "启动后面板开关即显示真实状态。", .pt: "Os interruptores do painel mostram o estado real logo após o início."])),
            ]),
            ChangelogEntry(version: "0.2.0", date: "2026-07-24", items: [
                ChangeItem(kind: .new, text: L("GitHub update check and the What's New window.", [.ru: "Проверка обновлений через GitHub и окно «Что нового».", .es: "Comprobación de actualizaciones por GitHub y ventana Novedades.", .fr: "Vérification des mises à jour via GitHub et fenêtre Nouveautés.", .de: "GitHub-Update-Prüfung und das Neuigkeiten-Fenster.", .ja: "GitHub 経由のアップデート確認と「新機能」ウインドウ。", .zh: "GitHub 更新检查与“新增内容”窗口。", .pt: "Verificação de atualizações via GitHub e a janela Novidades."])),
            ]),
            ChangelogEntry(version: "0.1.0", date: "2026-07-23", items: [
                ChangeItem(kind: .new, text: L("Keep Awake module: manual, timed or automatic (external display, power, chosen apps), closed-lid mode, battery guard, global hotkey.", [.ru: "Модуль «Не спать»: вручную, по таймеру или автоматически (внешний дисплей, питание, выбранные приложения), режим с закрытой крышкой, защита батареи, глобальный хоткей.", .es: "Módulo Mantener activo: manual, con temporizador o automático (pantalla externa, corriente, apps elegidas), tapa cerrada, protección de batería, atajo global.", .fr: "Module Rester éveillé : manuel, minuté ou automatique (écran externe, secteur, apps choisies), capot fermé, protection batterie, raccourci global.", .de: "Wach-halten-Modul: manuell, per Timer oder automatisch (externer Bildschirm, Netzstrom, gewählte Apps), geschlossener Deckel, Batterieschutz, globaler Kurzbefehl.", .ja: "スリープ防止モジュール：手動・タイマー・自動（外部ディスプレイ、電源、選択アプリ）、クラムシェル、バッテリー保護、グローバルショートカット。", .zh: "保持唤醒模块：手动、定时或自动（外接显示器、电源、指定应用）、合盖模式、电池保护、全局快捷键。", .pt: "Módulo Manter ativo: manual, por timer ou automático (tela externa, energia, apps escolhidos), tampa fechada, proteção de bateria, atalho global."])),
                ChangeItem(kind: .new, text: L("VPN module: connect and disconnect system VPNs with per-app auto-connect rules.", [.ru: "Модуль VPN: подключение и отключение системных VPN с авто-подключением по приложениям.", .es: "Módulo VPN: conecta y desconecta VPN del sistema con reglas por app.", .fr: "Module VPN : connexion/déconnexion des VPN système avec règles par app.", .de: "VPN-Modul: System-VPNs verbinden/trennen mit App-Regeln.", .ja: "VPN モジュール：システム VPN の接続/切断とアプリ別自動接続。", .zh: "VPN 模块：连接/断开系统 VPN，支持按应用自动连接。", .pt: "Módulo VPN: conecta e desconecta VPNs do sistema com regras por app."])),
                ChangeItem(kind: .new, text: L("Menu-bar panel and a System Settings-style window, the Liquid Glass icon, eight languages.", [.ru: "Панель в строке меню и окно в стиле Системных настроек, иконка Liquid Glass, восемь языков.", .es: "Panel en la barra y ventana al estilo Ajustes del Sistema, icono Liquid Glass, ocho idiomas.", .fr: "Panneau de barre des menus et fenêtre façon Réglages Système, icône Liquid Glass, huit langues.", .de: "Menüleisten-Panel und Fenster im Systemeinstellungen-Stil, Liquid-Glass-Symbol, acht Sprachen.", .ja: "メニューバーパネルとシステム設定風ウインドウ、Liquid Glass アイコン、8 言語対応。", .zh: "菜单栏面板与系统设置风格窗口、Liquid Glass 图标、八种语言。", .pt: "Painel na barra e janela no estilo Ajustes do Sistema, ícone Liquid Glass, oito idiomas."])),
            ]),
        ]
    }
}
