import HelmUI
import Module_Layout_Engine

enum LyStr {
    /// Broader than "layout" on purpose: the module id stays `layout`, but the
    /// name has room for whatever else belongs to the keyboard later.
    static var moduleName: String { L("Keyboard", [.ru: "Клавиатура", .es: "Teclado", .fr: "Clavier", .de: "Tastatur", .ja: "キーボード", .zh: "键盘", .pt: "Teclado"]) }
    static var summary: String { L("Fixes words typed in the wrong keyboard layout.", [.ru: "Исправляет слова, набранные не в той раскладке.", .es: "Corrige palabras escritas en la distribución equivocada.", .fr: "Corrige les mots tapés dans la mauvaise disposition.", .de: "Korrigiert Wörter, die in der falschen Belegung getippt wurden.", .ja: "誤った配列で入力した単語を修正します。", .zh: "修正用错误键盘布局输入的单词。", .pt: "Corrige palavras digitadas no layout errado."]) }
    static var automatic: String { L("Fix as I type", [.ru: "Исправлять по ходу набора", .es: "Corregir mientras escribo", .fr: "Corriger pendant la saisie", .de: "Beim Tippen korrigieren", .ja: "入力しながら修正", .zh: "输入时自动修正", .pt: "Corrigir enquanto digito"]) }
    static var automaticNote: String { L("A word is only changed when it is not a word as typed and is one once swapped. Anything valid is left alone.", [.ru: "Слово меняется, только если само по себе оно не слово, а после смены раскладки словом становится. Всё осмысленное остаётся как есть.", .es: "Una palabra solo cambia si no es palabra tal como se escribió y sí lo es al convertirla. Lo válido no se toca.", .fr: "Un mot n’est changé que s’il n’en est pas un tel quel et en devient un une fois converti. Ce qui est valide reste.", .de: "Ein Wort wird nur geändert, wenn es so getippt keines ist und nach dem Tausch eines wird. Gültiges bleibt.", .ja: "入力どおりでは単語でなく、変換すると単語になる場合のみ置き換えます。正しいものはそのままです。", .zh: "只有当按原样不是单词、转换后才是单词时才替换。有效的内容不会被改动。", .pt: "Uma palavra só muda se não for palavra como digitada e passar a ser após a troca. O que é válido fica."]) }
    static var needsAccessibility: String { L("Without Accessibility Helm cannot see what you type, and this does nothing.", [.ru: "Без универсального доступа Helm не видит набранное, и это не работает.", .es: "Sin Accesibilidad, Helm no ve lo que escribes y esto no funciona.", .fr: "Sans l’Accessibilité, Helm ne voit pas ce que vous tapez et ceci ne fait rien.", .de: "Ohne Bedienungshilfen sieht Helm nicht, was du tippst — das hier bleibt wirkungslos.", .ja: "アクセシビリティがないと入力内容を読み取れず、この機能は動作しません。", .zh: "没有辅助功能权限，Helm 无法读取输入，此功能不起作用。", .pt: "Sem Acessibilidade o Helm não vê o que você digita e isto não faz nada."]) }
    static var suspended: String { L("Paused — the system is in secure input.", [.ru: "Приостановлено — система в защищённом вводе.", .es: "En pausa: el sistema está en entrada segura.", .fr: "En pause — le système est en saisie sécurisée.", .de: "Pausiert — das System ist in sicherer Eingabe.", .ja: "一時停止中 — システムがセキュア入力です。", .zh: "已暂停——系统处于安全输入状态。", .pt: "Pausado — o sistema está em entrada segura."]) }
    static var exceptions: String { L("Never change these words", [.ru: "Никогда не менять эти слова", .es: "Nunca cambiar estas palabras", .fr: "Ne jamais changer ces mots", .de: "Diese Wörter nie ändern", .ja: "これらの単語は変更しない", .zh: "从不修改这些词", .pt: "Nunca alterar estas palavras"]) }
    static var exceptionsHint: String { L("One per line.", [.ru: "По одному в строке.", .es: "Uno por línea.", .fr: "Un par ligne.", .de: "Eines pro Zeile.", .ja: "1行に1つ。", .zh: "每行一个。", .pt: "Um por linha."]) }
    static var triggers: String { L("When to fix", [.ru: "Когда исправлять", .es: "Cuándo corregir", .fr: "Quand corriger", .de: "Wann korrigieren", .ja: "修正するタイミング", .zh: "何时修正", .pt: "Quando corrigir"]) }
    static var triggersHint: String { L("A word is checked when you finish it this way. Moving the caret or clicking elsewhere never converts — by then you have moved on.", [.ru: "Слово проверяется, когда вы закончили его одним из этих способов. Перемещение курсора или клик в другом месте не запускают проверку: к этому моменту вы уже заняты другим.", .es: "La palabra se revisa cuando la terminas así. Mover el cursor o hacer clic en otro sitio nunca convierte: ya te has ido.", .fr: "Le mot est vérifié quand vous le terminez ainsi. Déplacer le curseur ou cliquer ailleurs ne convertit jamais : vous êtes déjà parti.", .de: "Ein Wort wird geprüft, wenn du es so beendest. Cursor bewegen oder woanders klicken konvertiert nie — dann bist du schon weiter.", .ja: "この方法で単語を終えたときに判定します。カーソル移動や他所のクリックでは変換しません。既に離れているためです。", .zh: "以这些方式结束单词时才会判断。移动光标或点击别处从不转换——那时你已经离开了。", .pt: "A palavra é verificada quando você a termina assim. Mover o cursor ou clicar em outro lugar nunca converte — você já saiu."]) }
    static var onSpace: String { L("When Space is pressed", [.ru: "Когда нажат пробел", .es: "Al pulsar Espacio", .fr: "À l’appui sur Espace", .de: "Wenn die Leertaste gedrückt wird", .ja: "スペースキーを押したとき", .zh: "按下空格键时", .pt: "Ao pressionar Espaço"]) }
    static var onReturn: String { L("When Return is pressed", [.ru: "Когда нажат Return", .es: "Al pulsar Retorno", .fr: "À l’appui sur Retour", .de: "Wenn die Return-Taste gedrückt wird", .ja: "Return キーを押したとき", .zh: "按下 Return 键时", .pt: "Ao pressionar Retorno"]) }
    static var onPunctuation: String { L("When a punctuation mark is typed", [.ru: "Когда введён знак препинания", .es: "Al escribir un signo de puntuación", .fr: "À la saisie d’une ponctuation", .de: "Wenn ein Satzzeichen getippt wird", .ja: "句読点を入力したとき", .zh: "输入标点时", .pt: "Ao digitar um sinal de pontuação"]) }
    static var noAppsYet: String { L("No apps listed — it works everywhere except terminals and password managers.", [.ru: "Список пуст — работает везде, кроме терминалов и менеджеров паролей.", .es: "Lista vacía: funciona en todas partes salvo terminales y gestores de contraseñas.", .fr: "Liste vide — actif partout sauf terminaux et gestionnaires de mots de passe.", .de: "Liste leer — wirkt überall außer in Terminals und Passwortmanagern.", .ja: "一覧は空です。ターミナルとパスワード管理アプリ以外のすべてで動作します。", .zh: "列表为空——除终端和密码管理器外，在所有位置生效。", .pt: "Lista vazia — funciona em todo lugar, exceto terminais e gerenciadores de senha."]) }
    static var addApp: String { L("Add app…", [.ru: "Добавить программу…", .es: "Añadir app…", .fr: "Ajouter une app…", .de: "App hinzufügen…", .ja: "アプリを追加…", .zh: "添加应用…", .pt: "Adicionar app…"]) }
    static var ruleOn: String { L("Fix", [.ru: "Исправлять", .es: "Corregir", .fr: "Corriger", .de: "Korrigieren", .ja: "修正する", .zh: "修正", .pt: "Corrigir"]) }
    static var ruleOff: String { L("Don’t fix", [.ru: "Не исправлять", .es: "No corregir", .fr: "Ne pas corriger", .de: "Nicht korrigieren", .ja: "修正しない", .zh: "不修正", .pt: "Não corrigir"]) }
    static var shortcuts: String { L("Shortcuts", [.ru: "Горячие клавиши", .es: "Atajos", .fr: "Raccourcis", .de: "Kurzbefehle", .ja: "ショートカット", .zh: "快捷键", .pt: "Atalhos"]) }
    static var convertAction: String { L("Convert the last word", [.ru: "Сменить раскладку последнего слова", .es: "Convertir la última palabra", .fr: "Convertir le dernier mot", .de: "Letztes Wort umwandeln", .ja: "直前の単語を変換", .zh: "转换最后一个词", .pt: "Converter a última palavra"]) }
    static var undoAction: String { L("Undo the last change", [.ru: "Вернуть последнюю замену", .es: "Deshacer el último cambio", .fr: "Annuler le dernier changement", .de: "Letzte Änderung zurücknehmen", .ja: "直前の変更を元に戻す", .zh: "撤销最近一次修改", .pt: "Desfazer a última alteração"]) }
    static var apps: String { L("Rules for specific apps", [.ru: "Правила для отдельных программ", .es: "Reglas para apps concretas", .fr: "Règles par app", .de: "Regeln für einzelne Apps", .ja: "アプリごとのルール", .zh: "针对特定应用的规则", .pt: "Regras para apps específicos"]) }
    static var appsHint: String { L("Terminals and password managers are left alone: there, a wrong-looking word is often exactly right.", [.ru: "Терминалы и менеджеры паролей не трогаются: там странное на вид слово чаще всего именно то, что нужно.", .es: "Los terminales y gestores de contraseñas se dejan en paz: allí una palabra rara suele ser la correcta.", .fr: "Les terminaux et gestionnaires de mots de passe sont ignorés : un mot qui semble faux y est souvent exact.", .de: "Terminals und Passwortmanager bleiben unangetastet: dort ist ein seltsames Wort meist genau richtig.", .ja: "ターミナルとパスワード管理アプリは対象外です。そこでは不自然に見える語こそ正しいことが多いためです。", .zh: "终端和密码管理器不受影响：在那里，看起来奇怪的词往往正是对的。", .pt: "Terminais e gerenciadores de senha ficam de fora: ali, uma palavra estranha costuma ser a certa."]) }
    static var metricToday: String { L("TODAY", [.ru: "СЕГОДНЯ", .es: "HOY", .fr: "AUJOURD’HUI", .de: "HEUTE", .ja: "本日", .zh: "今日", .pt: "HOJE"]) }
    static var metricState: String { L("STATE", [.ru: "СОСТОЯНИЕ", .es: "ESTADO", .fr: "ÉTAT", .de: "STATUS", .ja: "状態", .zh: "状态", .pt: "ESTADO"]) }
    static var on: String { L("Running", [.ru: "Работает", .es: "Activo", .fr: "Actif", .de: "Aktiv", .ja: "動作中", .zh: "运行中", .pt: "Ativo"]) }
    static var notWatching: String { L("Not running", [.ru: "Не работает", .es: "Detenido", .fr: "Arrêté", .de: "Nicht aktiv", .ja: "停止中", .zh: "未运行", .pt: "Parado"]) }
    static var paused: String { L("Paused", [.ru: "Пауза", .es: "En pausa", .fr: "En pause", .de: "Pausiert", .ja: "一時停止", .zh: "已暂停", .pt: "Em pausa"]) }
    static var lastChange: String { L("Last change", [.ru: "Последняя замена", .es: "Último cambio", .fr: "Dernier changement", .de: "Letzte Änderung", .ja: "直近の変更", .zh: "最近一次修改", .pt: "Última alteração"]) }
    static var introTitle: String { L("Keyboard", [.ru: "Клавиатура", .es: "Teclado", .fr: "Clavier", .de: "Tastatur", .ja: "キーボード", .zh: "键盘", .pt: "Teclado"]) }
    static var introSubtitle: String { L("Before it starts changing what you type.", [.ru: "Что оно делает с вашим текстом — до того, как начнёт.", .es: "Antes de que empiece a cambiar lo que escribes.", .fr: "Avant qu’il ne commence à modifier ce que vous tapez.", .de: "Bevor es anfängt, dein Getipptes zu ändern.", .ja: "入力した文字を書き換える前に。", .zh: "在它开始改动你输入的文字之前。", .pt: "Antes de começar a mudar o que você digita."]) }
    static var introWhat: String { L("Type ghbdtn in the wrong layout and it becomes привет, with the input source switching to match.", [.ru: "Набрали ghbdtn, забыв переключить раскладку, — Helm заменит это на «привет» и переключит раскладку сам.", .es: "Escribe ghbdtn en la distribución equivocada y se convierte en привет; la fuente de entrada cambia con él.", .fr: "Tapez ghbdtn dans la mauvaise disposition : le mot devient привет, et la source de saisie suit.", .de: "Tippe ghbdtn in der falschen Belegung, und daraus wird привет — die Eingabequelle wechselt mit.", .ja: "配列を切り替え忘れて ghbdtn と入力すると、привет に直り、入力ソースも切り替わります。", .zh: "用错布局输入 ghbdtn，它会变成 привет，输入法也随之切换。", .pt: "Digite ghbdtn no layout errado e vira привет, com a fonte de entrada acompanhando."]) }
    static var introWhen: String { L("Only when what you typed is not a word and becomes one once the layout is switched. Anything that is already a word is left alone.", [.ru: "Только если набранное — не слово, а после смены раскладки словом становится. Всё, что осмысленно как есть, остаётся нетронутым.", .es: "Solo cuando lo escrito no es una palabra y sí lo es al cambiar de distribución. Lo que ya es una palabra no se toca.", .fr: "Uniquement si ce que vous avez tapé n’est pas un mot et en devient un une fois la disposition changée. Ce qui est déjà un mot reste intact.", .de: "Nur wenn das Getippte kein Wort ist und nach dem Belegungswechsel eines wird. Was schon ein Wort ist, bleibt unberührt.", .ja: "入力どおりでは単語でなく、配列を切り替えると単語になる場合だけです。すでに単語であるものには触れません。", .zh: "仅当按原样不是单词、切换布局后才是单词时才会改。已经是单词的一律不动。", .pt: "Só quando o que você digitou não é palavra e passa a ser depois de trocar o layout. O que já é palavra fica intacto."]) }
    static var introWhere: String { L("Never in terminals, password fields or password managers — there a strange-looking word is usually the right one.", [.ru: "Никогда — в терминалах, полях пароля и менеджерах паролей: там непонятный набор символов чаще всего и есть то, что нужно.", .es: "Nunca en terminales, campos de contraseña ni gestores de contraseñas: ahí una palabra rara suele ser la correcta.", .fr: "Jamais dans un terminal, un champ de mot de passe ou un gestionnaire de mots de passe : là, un mot bizarre est en général le bon.", .de: "Nie in Terminals, Passwortfeldern oder Passwortmanagern — dort ist ein seltsam aussehendes Wort meist das richtige.", .ja: "ターミナル、パスワード欄、パスワード管理アプリでは動きません。そこでは不可解な文字列こそが正しい入力です。", .zh: "在终端、密码框和密码管理器中从不介入——那里看起来奇怪的字符往往正是要输入的。", .pt: "Nunca em terminais, campos de senha ou gerenciadores de senha — ali uma palavra estranha costuma ser a certa."]) }
    static var introUndo: String { L("Every change can be undone — set the shortcut below. And there is a field on this page to try it in, before it touches anything real.", [.ru: "Любую замену можно отменить — горячая клавиша настраивается ниже. А ещё на этой странице есть поле, где всё можно попробовать до того, как модуль коснётся настоящего текста.", .es: "Cada cambio se puede deshacer — el atajo se configura abajo. Y en esta página hay un campo para probarlo antes de que toque nada real.", .fr: "Tout changement peut être annulé — le raccourci se règle ci-dessous. Et cette page contient un champ pour essayer, avant que rien de réel ne soit touché.", .de: "Jede Änderung lässt sich zurücknehmen — der Kurzbefehl wird unten festgelegt. Und auf dieser Seite gibt es ein Feld zum Ausprobieren, bevor echter Text berührt wird.", .ja: "変更はすべて元に戻せます。ショートカットは下で設定できます。このページには、実際の文章に触れる前に試せる入力欄もあります。", .zh: "任何改动都可以撤销——快捷键在下方设置。本页还有一个试用输入框，可以在它接触真实文字之前先试一试。", .pt: "Qualquer mudança pode ser desfeita — o atalho se configura abaixo. E nesta página há um campo para experimentar antes de tocar em algo real."]) }
    static var introStart: String { L("Got it", [.ru: "Понятно", .es: "Entendido", .fr: "Compris", .de: "Verstanden", .ja: "了解", .zh: "明白了", .pt: "Entendi"]) }
    static var tryIt: String { L("Try it", [.ru: "Попробовать", .es: "Pruébalo", .fr: "Essayer", .de: "Ausprobieren", .ja: "試す", .zh: "试一试", .pt: "Experimente"]) }
    static var tryItPlaceholder: String { L("Type ghbdtn and press space", [.ru: "Наберите ghbdtn и нажмите пробел", .es: "Escribe ghbdtn y pulsa espacio", .fr: "Tapez ghbdtn puis espace", .de: "Tippe ghbdtn und drücke die Leertaste", .ja: "ghbdtn と入力してスペースを押してください", .zh: "输入 ghbdtn 后按空格", .pt: "Digite ghbdtn e aperte espaço"]) }
    static var tryItHint: String { L("This is the real thing, not a demonstration: it works here exactly as it does anywhere else.", [.ru: "Поле настоящее, а не демонстрация: здесь модуль работает точно так же, как в любой другой программе.", .es: "El campo es real, no una demostración: aquí funciona igual que en cualquier otra app.", .fr: "Ce champ est réel, pas une démonstration : le module s’y comporte comme partout ailleurs.", .de: "Das Feld ist echt, keine Vorführung: hier arbeitet das Modul genau wie überall sonst.", .ja: "これはデモではなく本物の入力欄です。ここでも他のアプリと同じように動きます。", .zh: "这是真实的输入框，不是演示：它在这里的行为和在别处完全一样。", .pt: "O campo é real, não uma demonstração: aqui o módulo funciona como em qualquer outro app."]) }
    static var indicator: String { L("Language indicator", [.ru: "Индикатор языка", .es: "Indicador de idioma", .fr: "Indicateur de langue", .de: "Sprachanzeige", .ja: "入力ソース表示", .zh: "语言指示器", .pt: "Indicador de idioma"]) }
    static var indicatorShow: String { L("Show it in the menu bar", [.ru: "Показывать в строке меню", .es: "Mostrarlo en la barra de menús", .fr: "L’afficher dans la barre des menus", .de: "In der Menüleiste anzeigen", .ja: "メニューバーに表示", .zh: "在菜单栏中显示", .pt: "Mostrar na barra de menus"]) }
    static var indicatorHint: String { L("Helm's own copy of the menu-bar indicator, with the choices the system's one does not offer. macOS shows its own — turn that one off in Keyboard settings, or you get two.", [.ru: "Своя копия индикатора в строке меню — с настройками, которых нет у системного. Системный никуда не девается: выключите его в настройках клавиатуры, иначе их будет два.", .es: "Una copia propia del indicador con las opciones que el del sistema no ofrece. El del sistema sigue ahí: desactívalo en Ajustes de teclado o tendrás dos.", .fr: "Une copie de l’indicateur avec les choix que celui du système n’offre pas. Celui du système reste : désactivez-le dans les réglages du clavier, sinon vous en aurez deux.", .de: "Eine eigene Kopie der Anzeige, mit den Optionen, die die des Systems nicht bietet. Die des Systems bleibt: Schalte sie in den Tastatur-Einstellungen aus, sonst hast du zwei.", .ja: "システムの入力ソース表示を、設定できる形で複製したものです。システム側は残るので、キーボード設定でオフにしないと2つ並びます。", .zh: "菜单栏指示器的自有副本，带有系统版本没有的选项。系统的那个仍在：请在键盘设置中关闭，否则会有两个。", .pt: "Uma cópia própria do indicador, com as opções que o do sistema não oferece. O do sistema continua: desative-o nos Ajustes de teclado, ou você terá dois."]) }
    static var tapKey: String { L("One key for both", [.ru: "Одна клавиша на оба действия", .es: "Una tecla para ambos", .fr: "Une touche pour les deux", .de: "Eine Taste für beides", .ja: "ひとつのキーで両方", .zh: "一个键完成两件事", .pt: "Uma tecla para ambos"]) }
    static var tapKeyHint: String { L("Press and release it on its own: the first tap fixes the last word, the next puts it back. Held down or pressed with anything else it is still an ordinary modifier, so nothing you already use it for stops working.", [.ru: "Нажмите и отпустите её, ничего больше не нажимая: первое нажатие исправляет последнее слово, второе возвращает как было. Зажатая или нажатая вместе с чем-то ещё, она остаётся обычным модификатором — всё, для чего вы её уже используете, продолжает работать.", .es: "Púlsala y suéltala sola: la primera vez corrige la última palabra, la siguiente la devuelve. Mantenida o pulsada con otra tecla sigue siendo un modificador normal, así que nada de lo que ya haces con ella deja de funcionar.", .fr: "Appuyez puis relâchez-la seule : la première fois corrige le dernier mot, la suivante le restaure. Maintenue ou combinée, elle reste un modificateur ordinaire — rien de ce que vous en faites déjà ne cesse de fonctionner.", .de: "Allein drücken und loslassen: das erste Mal korrigiert das letzte Wort, das nächste stellt es zurück. Gehalten oder mit etwas anderem gedrückt bleibt sie ein gewöhnlicher Modifikator — nichts, wofür du sie schon benutzt, hört auf zu funktionieren.", .ja: "単独で押して離します。1 回目で直前の単語を修正し、もう一度で元に戻します。押しっぱなしや他のキーとの同時押しでは通常の修飾キーのままなので、いつもの使い方はそのまま生きています。", .zh: "单独按下再松开：第一次修正上一个词，再按一次还原。按住不放或与其他键同时按下时，它仍是普通的修饰键——你原有的用法不受影响。", .pt: "Pressione e solte sozinha: a primeira vez corrige a última palavra, a seguinte desfaz. Segurada ou junto com outra tecla, continua sendo um modificador comum — nada do que você já faz com ela deixa de funcionar."]) }
    static func tapKeyName(_ key: TapKey) -> String {
        switch key {
        case .off: return L("Off", [.ru: "Выключено", .es: "Desactivada", .fr: "Désactivée", .de: "Aus", .ja: "オフ", .zh: "关闭", .pt: "Desativada"])
        case .rightCommand: return L("Right ⌘", [.ru: "Правая ⌘", .es: "⌘ derecha", .fr: "⌘ droite", .de: "Rechte ⌘", .ja: "右 ⌘", .zh: "右 ⌘", .pt: "⌘ direita"])
        case .rightOption: return L("Right ⌥", [.ru: "Правая ⌥", .es: "⌥ derecha", .fr: "⌥ droite", .de: "Rechte ⌥", .ja: "右 ⌥", .zh: "右 ⌥", .pt: "⌥ direita"])
        case .rightControl: return L("Right ⌃", [.ru: "Правая ⌃", .es: "⌃ derecha", .fr: "⌃ droite", .de: "Rechte ⌃", .ja: "右 ⌃", .zh: "右 ⌃", .pt: "⌃ direita"])
        case .rightShift: return L("Right ⇧", [.ru: "Правая ⇧", .es: "⇧ derecha", .fr: "⇧ droite", .de: "Rechte ⇧", .ja: "右 ⇧", .zh: "右 ⇧", .pt: "⇧ direita"])
        }
    }
    static var badgeStyle: String { L("Style", [.ru: "Вид", .es: "Estilo", .fr: "Style", .de: "Stil", .ja: "スタイル", .zh: "样式", .pt: "Estilo"]) }
    static var badgeSize: String { L("Size", [.ru: "Размер", .es: "Tamaño", .fr: "Taille", .de: "Größe", .ja: "サイズ", .zh: "大小", .pt: "Tamanho"]) }
    static func badgeStyleName(_ style: BadgeStyle) -> String {
        switch style {
        case .plain: return L("Letters", [.ru: "Буквы", .es: "Letras", .fr: "Lettres", .de: "Buchstaben", .ja: "文字", .zh: "字母", .pt: "Letras"])
        case .filled: return L("Letters on a filled badge", [.ru: "Буквы на плашке", .es: "Letras sobre un fondo", .fr: "Lettres sur un fond", .de: "Buchstaben auf einer Fläche", .ja: "文字（背景あり）", .zh: "字母（实心底）", .pt: "Letras sobre um fundo"])
        case .outlined: return L("Letters in a frame", [.ru: "Буквы в рамке", .es: "Letras en un marco", .fr: "Lettres dans un cadre", .de: "Buchstaben in einem Rahmen", .ja: "文字（枠のみ）", .zh: "字母（描边框）", .pt: "Letras em uma moldura"])
        case .flagEmoji: return L("Flag, system", [.ru: "Флаг, системный", .es: "Bandera, del sistema", .fr: "Drapeau, système", .de: "Flagge, System", .ja: "旗（システム）", .zh: "旗帜（系统）", .pt: "Bandeira, do sistema"])
        case .flagDrawn: return L("Flag", [.ru: "Флаг", .es: "Bandera", .fr: "Drapeau", .de: "Flagge", .ja: "旗", .zh: "旗帜", .pt: "Bandeira"])
        }
    }
    static var badgePreview: String { L("Your layouts, as they will look:", [.ru: "Ваши раскладки — как они будут выглядеть:", .es: "Tus distribuciones, tal como se verán:", .fr: "Vos dispositions, telles qu’elles s’afficheront :", .de: "Deine Belegungen, so wie sie aussehen werden:", .ja: "インストール済みの配列の表示例：", .zh: "你的键盘布局，实际显示效果：", .pt: "Seus layouts, como vão aparecer:"]) }
    static var flagNote: String { L("A layout that names no country keeps its letters, in a frame the same size as a flag.", [.ru: "Раскладка, не привязанная к стране, остаётся буквами — в рамке размером с флаг.", .es: "Una distribución sin país conserva sus letras, en un marco del tamaño de una bandera.", .fr: "Une disposition sans pays garde ses lettres, dans un cadre de la taille d’un drapeau.", .de: "Eine Belegung ohne Land behält ihre Buchstaben, in einem Rahmen so groß wie eine Flagge.", .ja: "国が定まらない配列は文字のまま、旗と同じ大きさの枠に表示されます。", .zh: "没有国家归属的布局保持字母显示，边框与旗帜同样大小。", .pt: "Um layout sem país mantém as letras, numa moldura do tamanho de uma bandeira."]) }
    static var openKeyboardSettings: String { L("Open Keyboard settings…", [.ru: "Открыть настройки клавиатуры…", .es: "Abrir Ajustes de teclado…", .fr: "Ouvrir les réglages du clavier…", .de: "Tastatur-Einstellungen öffnen…", .ja: "キーボード設定を開く…", .zh: "打开键盘设置…", .pt: "Abrir Ajustes de teclado…"]) }
    static var neverThisWord: String { L("Never this word", [.ru: "Не менять это слово", .es: "Nunca esta palabra", .fr: "Jamais ce mot", .de: "Dieses Wort nie", .ja: "この単語は変更しない", .zh: "从不改这个词", .pt: "Nunca esta palavra"]) }
    static var audible: String { L("Play a sound when a word is fixed", [.ru: "Звук при исправлении слова", .es: "Sonido al corregir una palabra", .fr: "Son lors d’une correction", .de: "Ton bei einer Korrektur", .ja: "修正時に音を鳴らす", .zh: "修正时播放提示音", .pt: "Som ao corrigir uma palavra"]) }
    static var undoHint: String { L("Undo it with the shortcut below, in the app it happened in.", [.ru: "Отменяется горячей клавишей ниже — в том приложении, где произошла замена.", .es: "Se deshace con el atajo de abajo, en la app donde ocurrió.", .fr: "S’annule avec le raccourci ci-dessous, dans l’app où c’est arrivé.", .de: "Mit dem Kurzbefehl unten rückgängig zu machen — in der App, in der es passiert ist.", .ja: "下のショートカットで、置き換えが起きたアプリ内で元に戻せます。", .zh: "用下方快捷键在发生替换的应用中撤销。", .pt: "Desfaça pelo atalho abaixo, no app onde aconteceu."]) }
}
