import HelmUI
import Module_Layout_Engine

enum LyStr {
    /// Broader than "layout" on purpose: the module id stays `layout`, but the
    /// name has room for whatever else belongs to the keyboard later.
    static var moduleName: String { L("Keyboard", [.ru: "Клавиатура", .es: "Teclado", .fr: "Clavier", .de: "Tastatur", .ja: "キーボード", .zh: "键盘", .pt: "Teclado"]) }
    static var summary: String { L("Fixes words typed in the wrong keyboard layout.", [.ru: "Исправляет слова, набранные не в той раскладке.", .es: "Corrige palabras escritas en la distribución equivocada.", .fr: "Corrige les mots tapés dans la mauvaise disposition.", .de: "Korrigiert Wörter, die in der falschen Belegung getippt wurden.", .ja: "誤った配列で入力した単語を修正します。", .zh: "修正用错误键盘布局输入的单词。", .pt: "Corrige palavras digitadas no layout errado."]) }
    static var automatic: String { L("Fix as I type", [.ru: "Исправлять по ходу набора", .es: "Corregir mientras escribo", .fr: "Corriger pendant la saisie", .de: "Beim Tippen korrigieren", .ja: "入力しながら修正", .zh: "输入时自动修正", .pt: "Corrigir enquanto digito"]) }
    static var automaticNote: String { L("A word is only changed when it is not a word as typed and is one once swapped. Anything valid is left alone.", [.ru: "Слово меняется, только если как набрано оно не слово, а после перекладки — слово. Всё осмысленное остаётся как есть.", .es: "Una palabra solo cambia si no es palabra tal como se escribió y sí lo es al convertirla. Lo válido no se toca.", .fr: "Un mot n’est changé que s’il n’en est pas un tel quel et en devient un une fois converti. Ce qui est valide reste.", .de: "Ein Wort wird nur geändert, wenn es so getippt keines ist und nach dem Tausch eines wird. Gültiges bleibt.", .ja: "入力どおりでは単語でなく、変換すると単語になる場合のみ置き換えます。正しいものはそのままです。", .zh: "只有当按原样不是单词、转换后才是单词时才替换。有效的内容不会被改动。", .pt: "Uma palavra só muda se não for palavra como digitada e passar a ser após a troca. O que é válido fica."]) }
    static var needsAccessibility: String { L("Without Accessibility Helm cannot see what you type, and this does nothing.", [.ru: "Без универсального доступа Helm не видит набранное, и это не работает.", .es: "Sin Accesibilidad, Helm no ve lo que escribes y esto no funciona.", .fr: "Sans l’Accessibilité, Helm ne voit pas ce que vous tapez et ceci ne fait rien.", .de: "Ohne Bedienungshilfen sieht Helm nicht, was du tippst — das hier bleibt wirkungslos.", .ja: "アクセシビリティがないと入力内容を読み取れず、この機能は動作しません。", .zh: "没有辅助功能权限，Helm 无法读取输入，此功能不起作用。", .pt: "Sem Acessibilidade o Helm não vê o que você digita e isto não faz nada."]) }
    static var suspended: String { L("Paused — the system is in secure input.", [.ru: "Приостановлено — система в защищённом вводе.", .es: "En pausa: el sistema está en entrada segura.", .fr: "En pause — le système est en saisie sécurisée.", .de: "Pausiert — das System ist in sicherer Eingabe.", .ja: "一時停止中 — システムがセキュア入力です。", .zh: "已暂停——系统处于安全输入状态。", .pt: "Pausado — o sistema está em entrada segura."]) }
    static var exceptions: String { L("Never change these words", [.ru: "Никогда не менять эти слова", .es: "Nunca cambiar estas palabras", .fr: "Ne jamais changer ces mots", .de: "Diese Wörter nie ändern", .ja: "これらの単語は変更しない", .zh: "从不修改这些词", .pt: "Nunca alterar estas palavras"]) }
    static var exceptionsHint: String { L("One per line.", [.ru: "По одному в строке.", .es: "Uno por línea.", .fr: "Un par ligne.", .de: "Eines pro Zeile.", .ja: "1行に1つ。", .zh: "每行一个。", .pt: "Um por linha."]) }
    static var triggers: String { L("When to fix", [.ru: "Когда исправлять", .es: "Cuándo corregir", .fr: "Quand corriger", .de: "Wann korrigieren", .ja: "修正するタイミング", .zh: "何时修正", .pt: "Quando corrigir"]) }
    static var triggersHint: String { L("A word is checked when you finish it this way. Moving the caret or clicking elsewhere never converts — by then you have moved on.", [.ru: "Слово проверяется, когда вы завершили его так. Перемещение курсора или клик в другое место не конвертируют никогда — вы уже ушли дальше.", .es: "La palabra se revisa cuando la terminas así. Mover el cursor o hacer clic en otro sitio nunca convierte: ya te has ido.", .fr: "Le mot est vérifié quand vous le terminez ainsi. Déplacer le curseur ou cliquer ailleurs ne convertit jamais : vous êtes déjà parti.", .de: "Ein Wort wird geprüft, wenn du es so beendest. Cursor bewegen oder woanders klicken konvertiert nie — dann bist du schon weiter.", .ja: "この方法で単語を終えたときに判定します。カーソル移動や他所のクリックでは変換しません。既に離れているためです。", .zh: "以这些方式结束单词时才会判断。移动光标或点击别处从不转换——那时你已经离开了。", .pt: "A palavra é verificada quando você a termina assim. Mover o cursor ou clicar em outro lugar nunca converte — você já saiu."]) }
    static var onSpace: String { L("After a space", [.ru: "После пробела", .es: "Tras un espacio", .fr: "Après une espace", .de: "Nach einem Leerzeichen", .ja: "スペースの後", .zh: "空格之后", .pt: "Após um espaço"]) }
    static var onReturn: String { L("After Return", [.ru: "После ввода", .es: "Tras Retorno", .fr: "Après Retour", .de: "Nach Return", .ja: "Return の後", .zh: "回车之后", .pt: "Após Return"]) }
    static var onPunctuation: String { L("After punctuation", [.ru: "После знака препинания", .es: "Tras un signo de puntuación", .fr: "Après une ponctuation", .de: "Nach einem Satzzeichen", .ja: "句読点の後", .zh: "标点之后", .pt: "Após pontuação"]) }
    static var noAppsYet: String { L("No apps listed — it works everywhere except terminals and password managers.", [.ru: "Список пуст — работает везде, кроме терминалов и менеджеров паролей.", .es: "Lista vacía: funciona en todas partes salvo terminales y gestores de contraseñas.", .fr: "Liste vide — actif partout sauf terminaux et gestionnaires de mots de passe.", .de: "Liste leer — wirkt überall außer in Terminals und Passwortmanagern.", .ja: "一覧は空です。ターミナルとパスワード管理アプリ以外のすべてで動作します。", .zh: "列表为空——除终端和密码管理器外，在所有位置生效。", .pt: "Lista vazia — funciona em todo lugar, exceto terminais e gerenciadores de senha."]) }
    static var addApp: String { L("Add app…", [.ru: "Добавить программу…", .es: "Añadir app…", .fr: "Ajouter une app…", .de: "App hinzufügen…", .ja: "アプリを追加…", .zh: "添加应用…", .pt: "Adicionar app…"]) }
    static var ruleOn: String { L("Fix here", [.ru: "Исправлять", .es: "Corregir aquí", .fr: "Corriger ici", .de: "Hier korrigieren", .ja: "ここでは修正", .zh: "在此修正", .pt: "Corrigir aqui"]) }
    static var ruleOff: String { L("Leave alone", [.ru: "Не трогать", .es: "No tocar", .fr: "Ne pas toucher", .de: "Unangetastet", .ja: "触れない", .zh: "不处理", .pt: "Não mexer"]) }
    static var shortcuts: String { L("Shortcuts", [.ru: "Горячие клавиши", .es: "Atajos", .fr: "Raccourcis", .de: "Kurzbefehle", .ja: "ショートカット", .zh: "快捷键", .pt: "Atalhos"]) }
    static var convertAction: String { L("Convert the last word", [.ru: "Переложить последнее слово", .es: "Convertir la última palabra", .fr: "Convertir le dernier mot", .de: "Letztes Wort umwandeln", .ja: "直前の単語を変換", .zh: "转换最后一个词", .pt: "Converter a última palavra"]) }
    static var undoAction: String { L("Undo the last change", [.ru: "Вернуть последнюю замену", .es: "Deshacer el último cambio", .fr: "Annuler le dernier changement", .de: "Letzte Änderung zurücknehmen", .ja: "直前の変更を元に戻す", .zh: "撤销最近一次修改", .pt: "Desfazer a última alteração"]) }
    static var apps: String { L("Where it works", [.ru: "Где работает", .es: "Dónde funciona", .fr: "Où il agit", .de: "Wo es wirkt", .ja: "動作する場所", .zh: "生效范围", .pt: "Onde funciona"]) }
    static var appsHint: String { L("Terminals and password managers are left alone: there, a wrong-looking word is often exactly right.", [.ru: "Терминалы и менеджеры паролей не трогаются: там странное на вид слово чаще всего именно то, что нужно.", .es: "Los terminales y gestores de contraseñas se dejan en paz: allí una palabra rara suele ser la correcta.", .fr: "Les terminaux et gestionnaires de mots de passe sont ignorés : un mot qui semble faux y est souvent exact.", .de: "Terminals und Passwortmanager bleiben unangetastet: dort ist ein seltsames Wort meist genau richtig.", .ja: "ターミナルとパスワード管理アプリは対象外です。そこでは不自然に見える語こそ正しいことが多いためです。", .zh: "终端和密码管理器不受影响：在那里，看起来奇怪的词往往正是对的。", .pt: "Terminais e gerenciadores de senha ficam de fora: ali, uma palavra estranha costuma ser a certa."]) }
    static var metricToday: String { L("FIXED", [.ru: "ИСПРАВЛЕНО", .es: "CORREGIDO", .fr: "CORRIGÉ", .de: "KORRIGIERT", .ja: "修正", .zh: "已修正", .pt: "CORRIGIDO"]) }
    static var metricState: String { L("STATE", [.ru: "СОСТОЯНИЕ", .es: "ESTADO", .fr: "ÉTAT", .de: "STATUS", .ja: "状態", .zh: "状态", .pt: "ESTADO"]) }
    static var on: String { L("On", [.ru: "Вкл", .es: "Sí", .fr: "Oui", .de: "An", .ja: "オン", .zh: "开", .pt: "Sim"]) }
    static var notWatching: String { L("Not watching", [.ru: "Не следит", .es: "Sin vigilar", .fr: "Inactif", .de: "Beobachtet nicht", .ja: "監視していません", .zh: "未监视", .pt: "Sem monitorar"]) }
    static var paused: String { L("Paused", [.ru: "Пауза", .es: "Pausa", .fr: "Pause", .de: "Pause", .ja: "一時停止", .zh: "暂停", .pt: "Pausa"]) }
    static var lastChange: String { L("Last change", [.ru: "Последняя замена", .es: "Último cambio", .fr: "Dernier changement", .de: "Letzte Änderung", .ja: "直近の変更", .zh: "最近一次修改", .pt: "Última alteração"]) }
    static var introTitle: String { L("Keyboard", [.ru: "Клавиатура", .es: "Teclado", .fr: "Clavier", .de: "Tastatur", .ja: "キーボード", .zh: "键盘", .pt: "Teclado"]) }
    static var introSubtitle: String { L("Before it starts changing what you type.", [.ru: "Прежде чем оно начнёт менять набранное вами.", .es: "Antes de que empiece a cambiar lo que escribes.", .fr: "Avant qu’il ne commence à modifier ce que vous tapez.", .de: "Bevor es anfängt, dein Getipptes zu ändern.", .ja: "入力内容を書き換え始める前に。", .zh: "在它开始改动你输入的内容之前。", .pt: "Antes de começar a mudar o que você digita."]) }
    static var introWhat: String { L("Type ghbdtn in the wrong layout and it becomes привет, with the input source switching to match.", [.ru: "Наберёте ghbdtn не в той раскладке — станет привет, и раскладка переключится следом.", .es: "Escribe ghbdtn en la distribución equivocada y se convierte en привет, cambiando también la fuente de entrada.", .fr: "Tapez ghbdtn dans la mauvaise disposition et cela devient привет, la source de saisie suivant.", .de: "Tippe ghbdtn in der falschen Belegung, und es wird привет — die Eingabequelle wechselt mit.", .ja: "誤った配列で ghbdtn と入力すると привет になり、入力ソースも切り替わります。", .zh: "用错误布局输入 ghbdtn 会变成 привет，输入法也随之切换。", .pt: "Digite ghbdtn no layout errado e vira привет, com a fonte de entrada acompanhando."]) }
    static var introWhen: String { L("Only when what you typed is not a word and becomes one after the swap. Anything that is already a word is left alone.", [.ru: "Только если набранное — не слово, а после перекладки становится словом. Всё, что уже слово, не трогается.", .es: "Solo si lo que escribiste no es una palabra y sí lo es tras el cambio. Lo que ya es palabra no se toca.", .fr: "Seulement si ce que vous avez tapé n’est pas un mot et en devient un après conversion. Ce qui en est déjà un reste.", .de: "Nur wenn das Getippte kein Wort ist und nach dem Tausch eines wird. Was schon ein Wort ist, bleibt.", .ja: "入力どおりでは単語でなく、変換すると単語になる場合だけです。すでに単語のものは変更しません。", .zh: "仅当你输入的不是单词、转换后才是单词时。已经是单词的内容不会被改动。", .pt: "Só quando o que você digitou não é palavra e passa a ser após a troca. O que já é palavra fica."]) }
    static var introWhere: String { L("Never in terminals, password fields or password managers — there a strange-looking word is usually the right one.", [.ru: "Никогда в терминалах, полях пароля и менеджерах паролей — там странное на вид слово обычно и есть нужное.", .es: "Nunca en terminales, campos de contraseña ni gestores de contraseñas: allí una palabra rara suele ser la correcta.", .fr: "Jamais dans les terminaux, les champs de mot de passe ni les gestionnaires : un mot étrange y est souvent le bon.", .de: "Nie in Terminals, Passwortfeldern oder Passwortmanagern — dort ist ein seltsames Wort meist das richtige.", .ja: "ターミナル、パスワード欄、パスワード管理アプリでは動作しません。そこでは不自然な語こそ正しいためです。", .zh: "从不在终端、密码框和密码管理器中生效——那里看起来奇怪的词通常正是对的。", .pt: "Nunca em terminais, campos de senha ou gerenciadores de senha — ali uma palavra estranha costuma ser a certa."]) }
    static var introUndo: String { L("Every change can be undone with a shortcut, and any word can be added to a never-change list.", [.ru: "Любую замену можно вернуть горячей клавишей, а любое слово — занести в список «не менять».", .es: "Cada cambio se puede deshacer con un atajo, y cualquier palabra puede ir a la lista de intocables.", .fr: "Chaque changement s’annule par un raccourci, et tout mot peut rejoindre la liste des intouchables.", .de: "Jede Änderung lässt sich per Kurzbefehl zurücknehmen, und jedes Wort kann auf die Nie-ändern-Liste.", .ja: "変更はショートカットで元に戻せ、任意の単語を「変更しない」一覧に追加できます。", .zh: "每次修改都可用快捷键撤销，任何词都能加入「从不修改」列表。", .pt: "Toda mudança pode ser desfeita por atalho, e qualquer palavra pode ir para a lista de intocáveis."]) }
    static var introStart: String { L("Got it", [.ru: "Понятно", .es: "Entendido", .fr: "Compris", .de: "Verstanden", .ja: "了解", .zh: "明白了", .pt: "Entendi"]) }
    static var tryIt: String { L("Try it", [.ru: "Попробовать", .es: "Pruébalo", .fr: "Essayer", .de: "Ausprobieren", .ja: "試す", .zh: "试一试", .pt: "Experimente"]) }
    static var tryItPlaceholder: String { L("Type ghbdtn and press space", [.ru: "Наберите ghbdtn и нажмите пробел", .es: "Escribe ghbdtn y pulsa espacio", .fr: "Tapez ghbdtn puis espace", .de: "Tippe ghbdtn und drücke die Leertaste", .ja: "ghbdtn と入力してスペースを押してください", .zh: "输入 ghbdtn 后按空格", .pt: "Digite ghbdtn e aperte espaço"]) }
    static var tryItHint: String { L("This is the real thing, not a demonstration: it works here exactly as it does anywhere else.", [.ru: "Это настоящая работа модуля, а не показ: здесь он ведёт себя ровно так же, как везде.", .es: "Esto es real, no una demostración: aquí funciona exactamente igual que en cualquier sitio.", .fr: "C’est le vrai fonctionnement, pas une démonstration : ici comme ailleurs.", .de: "Das ist der echte Ablauf, keine Vorführung: hier verhält es sich wie überall.", .ja: "デモではなく実際の動作です。ここでも他と同じように動きます。", .zh: "这是真实运行，而非演示：在这里的行为与别处完全一致。", .pt: "Isto é real, não uma demonstração: aqui funciona exatamente como em qualquer lugar."]) }
    static var indicator: String { L("Language indicator", [.ru: "Индикатор языка", .es: "Indicador de idioma", .fr: "Indicateur de langue", .de: "Sprachanzeige", .ja: "入力ソース表示", .zh: "语言指示器", .pt: "Indicador de idioma"]) }
    static var indicatorHint: String { L("Helm's own copy of the menu-bar indicator, with the choices the system's one does not offer. macOS shows its own — turn that one off in Keyboard settings, or you get two.", [.ru: "Своя копия индикатора в строке меню — с настройками, которых нет у системного. Системный никуда не девается: выключите его в настройках клавиатуры, иначе их будет два.", .es: "Una copia propia del indicador con las opciones que el del sistema no ofrece. El del sistema sigue ahí: desactívalo en Ajustes de teclado o tendrás dos.", .fr: "Une copie de l’indicateur avec les choix que celui du système n’offre pas. Celui du système reste : désactivez-le dans les réglages du clavier, sinon vous en aurez deux.", .de: "Eine eigene Kopie der Anzeige, mit den Optionen, die die des Systems nicht bietet. Die des Systems bleibt: Schalte sie in den Tastatur-Einstellungen aus, sonst hast du zwei.", .ja: "システムの入力ソース表示を、設定できる形で複製したものです。システム側は残るので、キーボード設定でオフにしないと2つ並びます。", .zh: "菜单栏指示器的自有副本，带有系统版本没有的选项。系统的那个仍在：请在键盘设置中关闭，否则会有两个。", .pt: "Uma cópia própria do indicador, com as opções que o do sistema não oferece. O do sistema continua: desative-o nos Ajustes de teclado, ou você terá dois."]) }
    static var badgeStyle: String { L("Style", [.ru: "Вид", .es: "Estilo", .fr: "Style", .de: "Stil", .ja: "スタイル", .zh: "样式", .pt: "Estilo"]) }
    static var badgeSize: String { L("Size", [.ru: "Размер", .es: "Tamaño", .fr: "Taille", .de: "Größe", .ja: "サイズ", .zh: "大小", .pt: "Tamanho"]) }
    static func badgeStyleName(_ style: BadgeStyle) -> String {
        switch style {
        case .plain: return L("Letters", [.ru: "Буквы", .es: "Letras", .fr: "Lettres", .de: "Buchstaben", .ja: "文字", .zh: "字母", .pt: "Letras"])
        case .filled: return L("Letters, filled", [.ru: "Буквы с заливкой", .es: "Letras con relleno", .fr: "Lettres pleines", .de: "Buchstaben, gefüllt", .ja: "文字（塗り）", .zh: "字母（填充）", .pt: "Letras preenchidas"])
        case .outlined: return L("Letters, outlined", [.ru: "Буквы в контуре", .es: "Letras con contorno", .fr: "Lettres encadrées", .de: "Buchstaben, umrandet", .ja: "文字（枠線）", .zh: "字母（描边）", .pt: "Letras com contorno"])
        case .flagEmoji: return L("Flag, emoji", [.ru: "Флаг, эмодзи", .es: "Bandera, emoji", .fr: "Drapeau, emoji", .de: "Flagge, Emoji", .ja: "旗（絵文字）", .zh: "旗帜（表情）", .pt: "Bandeira, emoji"])
        case .flagDrawn: return L("Flag, drawn", [.ru: "Флаг, рисованный", .es: "Bandera, dibujada", .fr: "Drapeau, dessiné", .de: "Flagge, gezeichnet", .ja: "旗（描画）", .zh: "旗帜（绘制）", .pt: "Bandeira, desenhada"])
        }
    }
    static var flagNote: String { L("A layout with no country keeps its letters: a language is not a country, and guessing one is not Helm's place.", [.ru: "Раскладка без страны остаётся буквами: язык — не страна, и угадывать её Helm не станет.", .es: "Una distribución sin país conserva sus letras: un idioma no es un país, y adivinarlo no le toca a Helm.", .fr: "Une disposition sans pays garde ses lettres : une langue n’est pas un pays, et le deviner n’appartient pas à Helm.", .de: "Eine Belegung ohne Land behält ihre Buchstaben: Eine Sprache ist kein Land, und das zu raten steht Helm nicht zu.", .ja: "国が定まらない配列は文字のままです。言語は国ではなく、それを推測するのは Helm の役目ではありません。", .zh: "没有国家归属的布局保持字母显示：语言不等于国家，替它猜测不是 Helm 该做的事。", .pt: "Um layout sem país mantém as letras: um idioma não é um país, e adivinhá-lo não cabe ao Helm."]) }
    static var openKeyboardSettings: String { L("Open Keyboard settings…", [.ru: "Открыть настройки клавиатуры…", .es: "Abrir Ajustes de teclado…", .fr: "Ouvrir les réglages du clavier…", .de: "Tastatur-Einstellungen öffnen…", .ja: "キーボード設定を開く…", .zh: "打开键盘设置…", .pt: "Abrir Ajustes de teclado…"]) }
    static var neverThisWord: String { L("Never this word", [.ru: "Не менять это слово", .es: "Nunca esta palabra", .fr: "Jamais ce mot", .de: "Dieses Wort nie", .ja: "この単語は変更しない", .zh: "从不改这个词", .pt: "Nunca esta palavra"]) }
    static var audible: String { L("Play a sound when a word is fixed", [.ru: "Звук при исправлении слова", .es: "Sonido al corregir una palabra", .fr: "Son lors d’une correction", .de: "Ton bei einer Korrektur", .ja: "修正時に音を鳴らす", .zh: "修正时播放提示音", .pt: "Som ao corrigir uma palavra"]) }
    static var undoHint: String { L("Undo it with the shortcut below, in the app it happened in.", [.ru: "Отменяется горячей клавишей ниже — в том приложении, где произошла замена.", .es: "Se deshace con el atajo de abajo, en la app donde ocurrió.", .fr: "S’annule avec le raccourci ci-dessous, dans l’app où c’est arrivé.", .de: "Mit dem Kurzbefehl unten rückgängig zu machen — in der App, in der es passiert ist.", .ja: "下のショートカットで、置き換えが起きたアプリ内で元に戻せます。", .zh: "用下方快捷键在发生替换的应用中撤销。", .pt: "Desfaça pelo atalho abaixo, no app onde aconteceu."]) }
    static var undo: String { L("Undo", [.ru: "Вернуть", .es: "Deshacer", .fr: "Annuler", .de: "Rückgängig", .ja: "元に戻す", .zh: "撤销", .pt: "Desfazer"]) }
}
