import HelmUI

enum LyStr {
    static var moduleName: String { L("Layout", [.ru: "Раскладка", .es: "Distribución", .fr: "Disposition", .de: "Belegung", .ja: "キーボード配列", .zh: "键盘布局", .pt: "Layout"]) }
    static var summary: String { L("Fixes words typed in the wrong keyboard layout.", [.ru: "Исправляет слова, набранные не в той раскладке.", .es: "Corrige palabras escritas en la distribución equivocada.", .fr: "Corrige les mots tapés dans la mauvaise disposition.", .de: "Korrigiert Wörter, die in der falschen Belegung getippt wurden.", .ja: "誤った配列で入力した単語を修正します。", .zh: "修正用错误键盘布局输入的单词。", .pt: "Corrige palavras digitadas no layout errado."]) }
    static var automatic: String { L("Fix as I type", [.ru: "Исправлять по ходу набора", .es: "Corregir mientras escribo", .fr: "Corriger pendant la saisie", .de: "Beim Tippen korrigieren", .ja: "入力しながら修正", .zh: "输入时自动修正", .pt: "Corrigir enquanto digito"]) }
    static var automaticNote: String { L("A word is only changed when it is not a word as typed and is one once swapped. Anything valid is left alone.", [.ru: "Слово меняется, только если как набрано оно не слово, а после перекладки — слово. Всё осмысленное остаётся как есть.", .es: "Una palabra solo cambia si no es palabra tal como se escribió y sí lo es al convertirla. Lo válido no se toca.", .fr: "Un mot n’est changé que s’il n’en est pas un tel quel et en devient un une fois converti. Ce qui est valide reste.", .de: "Ein Wort wird nur geändert, wenn es so getippt keines ist und nach dem Tausch eines wird. Gültiges bleibt.", .ja: "入力どおりでは単語でなく、変換すると単語になる場合のみ置き換えます。正しいものはそのままです。", .zh: "只有当按原样不是单词、转换后才是单词时才替换。有效的内容不会被改动。", .pt: "Uma palavra só muda se não for palavra como digitada e passar a ser após a troca. O que é válido fica."]) }
    static var needsAccessibility: String { L("Without Accessibility Helm cannot see what you type, and this does nothing.", [.ru: "Без универсального доступа Helm не видит набранное, и это не работает.", .es: "Sin Accesibilidad, Helm no ve lo que escribes y esto no funciona.", .fr: "Sans l’Accessibilité, Helm ne voit pas ce que vous tapez et ceci ne fait rien.", .de: "Ohne Bedienungshilfen sieht Helm nicht, was du tippst — das hier bleibt wirkungslos.", .ja: "アクセシビリティがないと入力内容を読み取れず、この機能は動作しません。", .zh: "没有辅助功能权限，Helm 无法读取输入，此功能不起作用。", .pt: "Sem Acessibilidade o Helm não vê o que você digita e isto não faz nada."]) }
    static var suspended: String { L("Paused — the system is in secure input.", [.ru: "Приостановлено — система в защищённом вводе.", .es: "En pausa: el sistema está en entrada segura.", .fr: "En pause — le système est en saisie sécurisée.", .de: "Pausiert — das System ist in sicherer Eingabe.", .ja: "一時停止中 — システムがセキュア入力です。", .zh: "已暂停——系统处于安全输入状态。", .pt: "Pausado — o sistema está em entrada segura."]) }
    static var exceptions: String { L("Never change these words", [.ru: "Никогда не менять эти слова", .es: "Nunca cambiar estas palabras", .fr: "Ne jamais changer ces mots", .de: "Diese Wörter nie ändern", .ja: "これらの単語は変更しない", .zh: "从不修改这些词", .pt: "Nunca alterar estas palavras"]) }
    static var exceptionsHint: String { L("One per line.", [.ru: "По одному в строке.", .es: "Uno por línea.", .fr: "Un par ligne.", .de: "Eines pro Zeile.", .ja: "1行に1つ。", .zh: "每行一个。", .pt: "Um por linha."]) }
    static var apps: String { L("Where it works", [.ru: "Где работает", .es: "Dónde funciona", .fr: "Où il agit", .de: "Wo es wirkt", .ja: "動作する場所", .zh: "生效范围", .pt: "Onde funciona"]) }
    static var appsHint: String { L("Terminals and password managers are left alone: there, a wrong-looking word is often exactly right.", [.ru: "Терминалы и менеджеры паролей не трогаются: там странное на вид слово чаще всего именно то, что нужно.", .es: "Los terminales y gestores de contraseñas se dejan en paz: allí una palabra rara suele ser la correcta.", .fr: "Les terminaux et gestionnaires de mots de passe sont ignorés : un mot qui semble faux y est souvent exact.", .de: "Terminals und Passwortmanager bleiben unangetastet: dort ist ein seltsames Wort meist genau richtig.", .ja: "ターミナルとパスワード管理アプリは対象外です。そこでは不自然に見える語こそ正しいことが多いためです。", .zh: "终端和密码管理器不受影响：在那里，看起来奇怪的词往往正是对的。", .pt: "Terminais e gerenciadores de senha ficam de fora: ali, uma palavra estranha costuma ser a certa."]) }
    static var metricToday: String { L("FIXED", [.ru: "ИСПРАВЛЕНО", .es: "CORREGIDO", .fr: "CORRIGÉ", .de: "KORRIGIERT", .ja: "修正", .zh: "已修正", .pt: "CORRIGIDO"]) }
    static var metricState: String { L("STATE", [.ru: "СОСТОЯНИЕ", .es: "ESTADO", .fr: "ÉTAT", .de: "STATUS", .ja: "状態", .zh: "状态", .pt: "ESTADO"]) }
    static var on: String { L("On", [.ru: "Вкл", .es: "Sí", .fr: "Oui", .de: "An", .ja: "オン", .zh: "开", .pt: "Sim"]) }
    static var paused: String { L("Paused", [.ru: "Пауза", .es: "Pausa", .fr: "Pause", .de: "Pause", .ja: "一時停止", .zh: "暂停", .pt: "Pausa"]) }
    static var lastChange: String { L("Last change", [.ru: "Последняя замена", .es: "Último cambio", .fr: "Dernier changement", .de: "Letzte Änderung", .ja: "直近の変更", .zh: "最近一次修改", .pt: "Última alteração"]) }
    static var undo: String { L("Undo", [.ru: "Вернуть", .es: "Deshacer", .fr: "Annuler", .de: "Rückgängig", .ja: "元に戻す", .zh: "撤销", .pt: "Desfazer"]) }
}
