import HelmRuntime
import HelmUI

/// Every user-visible string in the duplicate finder, in eight languages.
enum DupStr {
    static var chooseFolder: String { L("Choose folder", [.ru: "Выбрать папку", .es: "Elegir carpeta", .fr: "Choisir un dossier", .de: "Ordner wählen", .ja: "フォルダを選択", .zh: "选择文件夹", .pt: "Escolher pasta"]) }
    static var chooseAnother: String { L("Choose another folder", [.ru: "Выбрать другую папку", .es: "Elegir otra carpeta", .fr: "Choisir un autre dossier", .de: "Anderen Ordner wählen", .ja: "別のフォルダを選択", .zh: "选择其他文件夹", .pt: "Escolher outra pasta"]) }
    static var search: String { L("Search", [.ru: "Искать", .es: "Buscar", .fr: "Rechercher", .de: "Suchen", .ja: "検索", .zh: "搜索", .pt: "Buscar"]) }
    static var searchAgain: String { L("Search again", [.ru: "Искать заново", .es: "Buscar de nuevo", .fr: "Rechercher à nouveau", .de: "Erneut suchen", .ja: "もう一度検索", .zh: "重新搜索", .pt: "Buscar de novo"]) }
    static var startHint: String { L("Pick a folder and Helm will read what is in it, comparing content rather than names.", [.ru: "Выберите папку — Helm прочитает, что в ней, сравнивая содержимое, а не имена.", .es: "Elige una carpeta y Helm leerá lo que hay en ella, comparando el contenido y no los nombres.", .fr: "Choisissez un dossier : Helm lira ce qu’il contient, en comparant le contenu et non les noms.", .de: "Wähle einen Ordner; Helm liest, was darin ist, und vergleicht den Inhalt, nicht die Namen.", .ja: "フォルダを選ぶと、名前ではなく中身を比較して調べます。", .zh: "选择一个文件夹，Helm 会读取其中内容并比较内容而非文件名。", .pt: "Escolha uma pasta e o Helm lerá o que há nela, comparando o conteúdo e não os nomes."]) }
    static var needsAccess: String { L("Without Full Disk Access the walk reads less, and a short answer looks exactly like a clean one.", [.ru: "Без полного доступа к диску обход прочитает меньше, а короткий ответ выглядит так же, как чистая папка.", .es: "Sin Acceso Total al Disco el recorrido lee menos, y una respuesta corta se ve igual que una carpeta limpia.", .fr: "Sans accès complet au disque, le parcours lit moins, et une réponse courte ressemble exactement à un dossier propre.", .de: "Ohne Festplattenvollzugriff liest der Durchlauf weniger — und eine kurze Antwort sieht aus wie ein sauberer Ordner.", .ja: "フルディスクアクセスがないと調べられる範囲が狭くなり、少ない結果が「重複なし」と見分けられません。", .zh: "没有完全磁盘访问权限时，遍历能读到的更少，而结果少看起来和「没有重复」一模一样。", .pt: "Sem Acesso Total ao Disco a varredura lê menos, e uma resposta curta parece exatamente uma pasta limpa."]) }
    static var stop: String { L("Stop", [.ru: "Остановить", .es: "Detener", .fr: "Arrêter", .de: "Stoppen", .ja: "停止", .zh: "停止", .pt: "Parar"]) }
    static var basket: String { L("To remove", [.ru: "К удалению", .es: "Para eliminar", .fr: "À supprimer", .de: "Zu entfernen", .ja: "削除予定", .zh: "待删除", .pt: "Para remover"]) }
    static var moveToTrash: String { L("Move to Trash", [.ru: "Переместить в Корзину", .es: "Mover a la Papelera", .fr: "Placer dans la corbeille", .de: "In den Papierkorb", .ja: "ゴミ箱に入れる", .zh: "移到废纸篓", .pt: "Mover para o Lixo"]) }
    static var systemItem: String { L("System item", [.ru: "Системный", .es: "Del sistema", .fr: "Élément système", .de: "Systemobjekt", .ja: "システム項目", .zh: "系统项目", .pt: "Item do sistema"]) }
    static var reveal: String { L("Show in Finder", [.ru: "Показать в Finder", .es: "Mostrar en Finder", .fr: "Afficher dans le Finder", .de: "Im Finder zeigen", .ja: "Finder で表示", .zh: "在访达中显示", .pt: "Mostrar no Finder"]) }
    static func removed(_ count: Int, _ freed: String) -> String {
        let files = Plural.files(count, language: AppLanguage.current.rawValue)
        return L("Removed \(files), \(freed) freed", [.ru: "Удалено \(files), освобождено \(freed)", .es: "Eliminados \(files), \(freed) liberados", .fr: "\(files) supprimés, \(freed) libérés", .de: "\(files) entfernt, \(freed) frei", .ja: "\(files)を削除、\(freed) 解放", .zh: "已删除\(files)，释放 \(freed)", .pt: "\(files) removidos, \(freed) liberados"])
    }
    static func removedWithFailures(_ removed: Int, _ failed: Int) -> String { L("Removed \(removed); \(failed) refused", [.ru: "Удалено \(removed); отказано в \(failed)", .es: "Eliminados \(removed); \(failed) rechazados", .fr: "\(removed) supprimés ; \(failed) refusés", .de: "\(removed) entfernt; \(failed) abgelehnt", .ja: "\(removed) 件削除、\(failed) 件は拒否", .zh: "已删除 \(removed) 个；\(failed) 个被拒绝", .pt: "\(removed) removidos; \(failed) recusados"]) }
    static func confirmTrash(_ count: Int, _ size: String) -> String {
        let files = Plural.files(count, language: AppLanguage.current.rawValue)
        return L("Move \(files) to the Trash? That frees \(size).", [.ru: "Переместить \(files) в Корзину? Освободится \(size).", .es: "¿Mover \(files) a la Papelera? Libera \(size).", .fr: "Placer \(files) dans la corbeille ? Cela libère \(size).", .de: "\(files) in den Papierkorb? Das gibt \(size) frei.", .ja: "\(files)をゴミ箱に入れますか？ \(size) が解放されます。", .zh: "把\(files)移到废纸篓？将释放 \(size)。", .pt: "Mover \(files) para o Lixo? Isso libera \(size)."])
    }
    static var moduleName: String { L("Duplicates", [.ru: "Дубликаты", .es: "Duplicados", .fr: "Doublons", .de: "Duplikate", .ja: "重複", .zh: "重复文件", .pt: "Duplicatas"]) }
    static var summary: String { L("Files that exist more than once", [.ru: "Файлы, которые существуют больше одного раза", .es: "Archivos que existen más de una vez", .fr: "Fichiers présents plus d’une fois", .de: "Dateien, die mehr als einmal existieren", .ja: "複数存在するファイル", .zh: "存在多份的文件", .pt: "Arquivos que existem mais de uma vez"]) }
    static var searching: String { L("Reading files…", [.ru: "Чтение файлов…", .es: "Leyendo archivos…", .fr: "Lecture des fichiers…", .de: "Dateien werden gelesen…", .ja: "ファイルを読み込み中…", .zh: "正在读取文件…", .pt: "Lendo arquivos…"]) }
    static func progressLine(_ done: Int, _ total: Int) -> String { L("\(done) of \(total) checks done", [.ru: "Проверок сделано: \(done) из \(total)", .es: "\(done) de \(total) comprobaciones hechas", .fr: "\(done) vérifications sur \(total)", .de: "\(done) von \(total) Prüfungen erledigt", .ja: "\(total) 件中 \(done) 件を確認済み", .zh: "已完成 \(done) / \(total) 项检查", .pt: "\(done) de \(total) verificações feitas"]) }
    static var none: String { L("No duplicates here. Every large file under this folder is one of a kind.", [.ru: "Дубликатов нет. Каждый крупный файл в этой папке существует в единственном экземпляре.", .es: "No hay duplicados. Cada archivo grande de esta carpeta es único.", .fr: "Aucun doublon. Chaque gros fichier de ce dossier est unique.", .de: "Keine Duplikate. Jede große Datei in diesem Ordner gibt es genau einmal.", .ja: "重複はありません。このフォルダの大きなファイルはすべて 1 つだけです。", .zh: "没有重复文件。此文件夹下的每个大文件都只有一份。", .pt: "Sem duplicatas. Cada arquivo grande nesta pasta é único."]) }
    static var floorNote: String { L("Files from 1 MB. Hard links are one file and are never offered.", [.ru: "Файлы от 1 МБ. Жёсткие ссылки — это один файл, они не предлагаются.", .es: "Archivos desde 1 MB. Los enlaces duros son un solo archivo y nunca se ofrecen.", .fr: "Fichiers à partir de 1 Mo. Les liens durs sont un seul fichier et ne sont jamais proposés.", .de: "Dateien ab 1 MB. Harte Links sind eine Datei und werden nie angeboten.", .ja: "1 MB 以上のファイルが対象。ハードリンクは同一ファイルなので提案されません。", .zh: "1 MB 以上的文件。硬链接是同一个文件，不会被列出。", .pt: "Arquivos a partir de 1 MB. Links físicos são um só arquivo e nunca são oferecidos."]) }
    static func found(_ groups: Int, _ wasted: String) -> String { L("Groups: \(groups) · \(wasted) recoverable", [.ru: "Групп: \(groups) · можно освободить \(wasted)", .es: "Grupos: \(groups) · \(wasted) recuperables", .fr: "Groupes : \(groups) · \(wasted) récupérables", .de: "Gruppen: \(groups) · \(wasted) freizugeben", .ja: "\(groups) グループ · \(wasted) 解放可能", .zh: "\(groups) 组 · 可释放 \(wasted)", .pt: "Grupos: \(groups) · \(wasted) recuperáveis"]) }
    static var keepWhy: String { L("The first path in alphabetical order. Helm never offers every copy of a file.", [.ru: "Первый путь по алфавиту. Helm никогда не предлагает удалить все копии файла.", .es: "La primera ruta en orden alfabético. Helm nunca ofrece todas las copias de un archivo.", .fr: "Le premier chemin par ordre alphabétique. Helm ne propose jamais toutes les copies d’un fichier.", .de: "Der alphabetisch erste Pfad. Helm bietet nie alle Kopien einer Datei an.", .ja: "アルファベット順で最初のパスです。Helm がすべてのコピーを削除対象にすることはありません。", .zh: "按字母顺序排在最前的路径。Helm 绝不会把文件的所有副本都列为可删。", .pt: "O primeiro caminho em ordem alfabética. O Helm nunca oferece todas as cópias de um arquivo."]) }
    static var keep: String { L("stays", [.ru: "останется", .es: "se queda", .fr: "reste", .de: "bleibt", .ja: "残す", .zh: "保留", .pt: "fica"]) }
    static var basketExtras: String { L("Extras to basket", [.ru: "Лишние — к удалению", .es: "Sobrantes a la cesta", .fr: "Les surplus au panier", .de: "Überzählige in den Korb", .ja: "余分をバスケットへ", .zh: "多余的放入收集篮", .pt: "Excedentes para a cesta"]) }
    static var cancel: String { L("Cancel", [.ru: "Отменить", .es: "Cancelar", .fr: "Annuler", .de: "Abbrechen", .ja: "キャンセル", .zh: "取消", .pt: "Cancelar"]) }
    static var close: String { L("Close", [.ru: "Закрыть", .es: "Cerrar", .fr: "Fermer", .de: "Schließen", .ja: "閉じる", .zh: "关闭", .pt: "Fechar"]) }
}
