import HelmUI

enum DkStr {
    static var moduleName: String { L("Disk Space", [.ru: "Место на диске", .es: "Espacio en disco", .fr: "Espace disque", .de: "Speicherplatz", .ja: "ディスク容量", .zh: "磁盘空间", .pt: "Espaço em disco"]) }
    static var summary: String { L("See what filled the disk, then reclaim it.", [.ru: "Увидеть, чем занят диск, и освободить место.", .es: "Mira qué llenó el disco y recupera espacio.", .fr: "Voyez ce qui remplit le disque, puis récupérez de l’espace.", .de: "Sehen, was die Platte füllt, und Platz zurückgewinnen.", .ja: "ディスクを埋めているものを確認し、容量を取り戻します。", .zh: "看清磁盘被什么占满，并回收空间。", .pt: "Veja o que encheu o disco e recupere espaço."]) }
    static var scanFolder: String { L("Scan a folder…", [.ru: "Сканировать папку…", .es: "Analizar una carpeta…", .fr: "Analyser un dossier…", .de: "Ordner scannen…", .ja: "フォルダをスキャン…", .zh: "扫描文件夹…", .pt: "Analisar uma pasta…"]) }
    static var scanning: String { L("Scanning", [.ru: "Сканирование", .es: "Analizando", .fr: "Analyse", .de: "Scan läuft", .ja: "スキャン中", .zh: "正在扫描", .pt: "Analisando"]) }
    static var cancel: String { L("Cancel", [.ru: "Отменить", .es: "Cancelar", .fr: "Annuler", .de: "Abbrechen", .ja: "キャンセル", .zh: "取消", .pt: "Cancelar"]) }
    static var newScan: String { L("New scan", [.ru: "Новое сканирование", .es: "Nuevo análisis", .fr: "Nouvelle analyse", .de: "Neuer Scan", .ja: "新規スキャン", .zh: "重新扫描", .pt: "Nova análise"]) }
    static var free: String { L("free", [.ru: "свободно", .es: "libre", .fr: "libre", .de: "frei", .ja: "空き", .zh: "可用", .pt: "livre"]) }
    static var basket: String { L("To remove", [.ru: "К удалению", .es: "Para eliminar", .fr: "À supprimer", .de: "Zu entfernen", .ja: "削除予定", .zh: "待删除", .pt: "Para remover"]) }
    static var moveToTrash: String { L("Move to Trash", [.ru: "Переместить в Корзину", .es: "Mover a la Papelera", .fr: "Placer dans la corbeille", .de: "In den Papierkorb", .ja: "ゴミ箱に入れる", .zh: "移到废纸篓", .pt: "Mover para o Lixo"]) }
    static var emptyBasket: String { L("Add files from the list to remove them together.", [.ru: "Добавляйте файлы из списка, чтобы удалить их вместе.", .es: "Añade archivos de la lista para eliminarlos juntos.", .fr: "Ajoutez des fichiers depuis la liste pour les supprimer ensemble.", .de: "Dateien aus der Liste hinzufügen, um sie gemeinsam zu entfernen.", .ja: "リストからファイルを追加して、まとめて削除します。", .zh: "从列表添加文件，一起删除。", .pt: "Adicione arquivos da lista para removê-los juntos."]) }
    static var addToBasket: String { L("Add", [.ru: "Добавить", .es: "Añadir", .fr: "Ajouter", .de: "Hinzufügen", .ja: "追加", .zh: "添加", .pt: "Adicionar"]) }
    static var systemItem: String { L("System — cannot be removed", [.ru: "Системный — удалить нельзя", .es: "Sistema: no se puede eliminar", .fr: "Système — non supprimable", .de: "System — nicht entfernbar", .ja: "システム — 削除できません", .zh: "系统项 — 无法删除", .pt: "Sistema — não pode ser removido"]) }
    static var noAccess: String { L("No access", [.ru: "Нет доступа", .es: "Sin acceso", .fr: "Pas d’accès", .de: "Kein Zugriff", .ja: "アクセス不可", .zh: "无访问权限", .pt: "Sem acesso"]) }
    static var reveal: String { L("Show in Finder", [.ru: "Показать в Finder", .es: "Mostrar en Finder", .fr: "Afficher dans le Finder", .de: "Im Finder zeigen", .ja: "Finder に表示", .zh: "在访达中显示", .pt: "Mostrar no Finder"]) }
    static var startHint: String { L("Pick a volume, or scan any folder.", [.ru: "Выберите том или просканируйте любую папку.", .es: "Elige un volumen o analiza cualquier carpeta.", .fr: "Choisissez un volume ou analysez un dossier.", .de: "Volume wählen oder einen beliebigen Ordner scannen.", .ja: "ボリュームを選ぶか、任意のフォルダをスキャンします。", .zh: "选择宗卷，或扫描任意文件夹。", .pt: "Escolha um volume ou analise qualquer pasta."]) }
    static func scannedIn(_ files: Int, _ seconds: String) -> String { L("\(files) files in \(seconds)", [.ru: "Файлов: \(files) за \(seconds)", .es: "\(files) archivos en \(seconds)", .fr: "\(files) fichiers en \(seconds)", .de: "\(files) Dateien in \(seconds)", .ja: "\(files) ファイル / \(seconds)", .zh: "\(files) 个文件，用时 \(seconds)", .pt: "\(files) arquivos em \(seconds)"]) }
    static func removedFreed(_ size: String) -> String { L("Removed — \(size) freed", [.ru: "Удалено — освобождено \(size)", .es: "Eliminado — \(size) liberados", .fr: "Supprimé — \(size) libérés", .de: "Entfernt — \(size) frei", .ja: "削除しました — \(size) を解放", .zh: "已删除 — 释放 \(size)", .pt: "Removido — \(size) liberados"]) }
    static func confirmTrash(_ count: Int, _ size: String) -> String { L("Move \(count) items (\(size)) to the Trash?", [.ru: "Переместить \(count) объектов (\(size)) в Корзину?", .es: "¿Mover \(count) elementos (\(size)) a la Papelera?", .fr: "Placer \(count) éléments (\(size)) dans la corbeille ?", .de: "\(count) Objekte (\(size)) in den Papierkorb legen?", .ja: "\(count) 項目（\(size)）をゴミ箱に入れますか？", .zh: "将 \(count) 项（\(size)）移到废纸篓？", .pt: "Mover \(count) itens (\(size)) para o Lixo?"]) }
    static func measured(_ ago: String) -> String { L("Measured \(ago)", [.ru: "Измерено \(ago)", .es: "Medido \(ago)", .fr: "Mesuré \(ago)", .de: "Gemessen \(ago)", .ja: "計測 \(ago)", .zh: "测量于 \(ago)", .pt: "Medido \(ago)"]) }
    static var rescan: String { L("Rescan", [.ru: "Пересканировать", .es: "Volver a escanear", .fr: "Réanalyser", .de: "Neu scannen", .ja: "再スキャン", .zh: "重新扫描", .pt: "Reescanear"]) }
    static var advice: String { L("Recommendations", [.ru: "Рекомендации", .es: "Recomendaciones", .fr: "Recommandations", .de: "Empfehlungen", .ja: "おすすめ", .zh: "建议", .pt: "Recomendações"]) }
    static var adviceHint: String { L("What could be deleted", [.ru: "Что можно удалить", .es: "Qué se podría eliminar", .fr: "Ce qui pourrait être supprimé", .de: "Was gelöscht werden könnte", .ja: "削除できる候補", .zh: "可删除的内容", .pt: "O que pode ser excluído"]) }
    static var adviceKindCache: String { L("Cache — safe to clear", [.ru: "Кеш — можно очистить", .es: "Caché — se puede limpiar", .fr: "Cache — peut être vidé", .de: "Cache — kann geleert werden", .ja: "キャッシュ — 削除可能", .zh: "缓存 — 可清理", .pt: "Cache — pode limpar"]) }
    static var adviceKindOldDownload: String { L("Old download", [.ru: "Старая загрузка", .es: "Descarga antigua", .fr: "Téléchargement ancien", .de: "Alter Download", .ja: "古いダウンロード", .zh: "旧下载", .pt: "Download antigo"]) }
    static var adviceKindLargeOld: String { L("Large, untouched for months", [.ru: "Большой, давно не использовался", .es: "Grande, sin usar hace meses", .fr: "Volumineux, inutilisé depuis des mois", .de: "Groß, seit Monaten unberührt", .ja: "大きく、長期間未使用", .zh: "大文件，数月未用", .pt: "Grande, sem uso há meses"]) }
    static var otherItems: String { L("Smaller items", [.ru: "Мелкие объекты", .es: "Elementos pequeños", .fr: "Petits éléments", .de: "Kleinere Objekte", .ja: "小さい項目", .zh: "较小的项目", .pt: "Itens menores"]) }
    static var back: String { L("Back", [.ru: "Назад", .es: "Atrás", .fr: "Retour", .de: "Zurück", .ja: "戻る", .zh: "返回", .pt: "Voltar"]) }
    static func liveCount(_ files: Int) -> String { L("\(files) files", [.ru: "Файлов: \(files)", .es: "\(files) archivos", .fr: "\(files) fichiers", .de: "\(files) Dateien", .ja: "\(files) ファイル", .zh: "\(files) 个文件", .pt: "\(files) arquivos"]) }
}
