import HelmRuntime
import HelmUI

enum DkStr {
    /// The display name only — the module id stays `disk`, or every stored
    /// setting keyed to it would be orphaned.
    static var moduleName: String { L("Disk", [.ru: "Диск", .es: "Disco", .fr: "Disque", .de: "Festplatte", .ja: "ディスク", .zh: "磁盘", .pt: "Disco"]) }
    static var summary: String { L("What is taking up space.", [.ru: "Что занимает место на диске.", .es: "Qué ocupa espacio en el disco.", .fr: "Ce qui occupe l’espace disque.", .de: "Was den Speicherplatz belegt.", .ja: "ディスクを占めているもの。", .zh: "磁盘空间被什么占用。", .pt: "O que ocupa espaço no disco."]) }
    static var scanFolder: String { L("Scan a folder…", [.ru: "Сканировать папку…", .es: "Analizar una carpeta…", .fr: "Analyser un dossier…", .de: "Ordner scannen…", .ja: "フォルダをスキャン…", .zh: "扫描文件夹…", .pt: "Analisar uma pasta…"]) }
    static var scanning: String { L("Scanning", [.ru: "Сканирование", .es: "Analizando", .fr: "Analyse", .de: "Scan läuft", .ja: "スキャン中", .zh: "正在扫描", .pt: "Analisando"]) }
    static var stop: String { L("Stop", [.ru: "Остановить", .es: "Detener", .fr: "Arrêter", .de: "Stoppen", .ja: "停止", .zh: "停止", .pt: "Parar"]) }
    static var cancel: String { L("Cancel", [.ru: "Отменить", .es: "Cancelar", .fr: "Annuler", .de: "Abbrechen", .ja: "キャンセル", .zh: "取消", .pt: "Cancelar"]) }
    static var scanAgain: String { L("Scan again", [.ru: "Сканировать заново", .es: "Escanear de nuevo", .fr: "Réanalyser", .de: "Erneut scannen", .ja: "再スキャン", .zh: "重新扫描", .pt: "Escanear de novo"]) }
    static var free: String { L("free", [.ru: "свободно", .es: "libre", .fr: "libre", .de: "frei", .ja: "空き", .zh: "可用", .pt: "livre"]) }
    static var basket: String { L("To remove", [.ru: "К удалению", .es: "Para eliminar", .fr: "À supprimer", .de: "Zu entfernen", .ja: "削除予定", .zh: "待删除", .pt: "Para remover"]) }
    static var moveToTrash: String { L("Move to Trash", [.ru: "Переместить в Корзину", .es: "Mover a la Papelera", .fr: "Placer dans la corbeille", .de: "In den Papierkorb", .ja: "ゴミ箱に入れる", .zh: "移到废纸篓", .pt: "Mover para o Lixo"]) }
    static var basketContents: String { L("Show what is in the basket", [.ru: "Показать, что отобрано к удалению", .es: "Ver qué hay en la cesta", .fr: "Voir le contenu du panier", .de: "Inhalt des Korbs zeigen", .ja: "バスケットの中身を表示", .zh: "查看收集篮内容", .pt: "Ver o que está na cesta"]) }
    static var couldNotMove: String { L("macOS refused", [.ru: "macOS отказал", .es: "macOS lo rechazó", .fr: "macOS a refusé", .de: "macOS hat abgelehnt", .ja: "macOS が拒否", .zh: "macOS 拒绝", .pt: "o macOS recusou"]) }
    static var emptyBasket: String { L("Nothing selected", [.ru: "Ничего не выбрано", .es: "Nada seleccionado", .fr: "Rien de sélectionné", .de: "Nichts ausgewählt", .ja: "未選択", .zh: "未选择任何项", .pt: "Nada selecionado"]) }
    static var addToBasket: String { L("Add", [.ru: "Добавить", .es: "Añadir", .fr: "Ajouter", .de: "Hinzufügen", .ja: "追加", .zh: "添加", .pt: "Adicionar"]) }
    static var systemItem: String { L("System", [.ru: "Системный", .es: "Del sistema", .fr: "Système", .de: "System", .ja: "システム", .zh: "系统", .pt: "Do sistema"]) }
    static var noAccess: String { L("No access", [.ru: "Нет доступа", .es: "Sin acceso", .fr: "Pas d’accès", .de: "Kein Zugriff", .ja: "アクセス不可", .zh: "无访问权限", .pt: "Sem acesso"]) }
    static var reveal: String { L("Show in Finder", [.ru: "Показать в Finder", .es: "Mostrar en Finder", .fr: "Afficher dans le Finder", .de: "Im Finder zeigen", .ja: "Finder に表示", .zh: "在访达中显示", .pt: "Mostrar no Finder"]) }
    static var scanNeedsAccess: String { L("Without Full Disk Access some folders scan as empty.", [.ru: "Без полного доступа к диску часть папок будет показана пустыми.", .es: "Sin Acceso Total al Disco algunas carpetas aparecerán vacías.", .fr: "Sans accès complet au disque, certains dossiers apparaîtront vides.", .de: "Ohne Festplattenvollzugriff erscheinen manche Ordner leer.", .ja: "フルディスクアクセスがないと、一部のフォルダは空として表示されます。", .zh: "没有完全磁盘访问权限时，部分文件夹会显示为空。", .pt: "Sem Acesso Total ao Disco algumas pastas aparecerão vazias."]) }
    static var startHint: String { L("Pick a volume, or scan any folder.", [.ru: "Выберите том или просканируйте любую папку.", .es: "Elige un volumen o analiza cualquier carpeta.", .fr: "Choisissez un volume ou analysez un dossier.", .de: "Volume wählen oder einen beliebigen Ordner scannen.", .ja: "ボリュームを選ぶか、任意のフォルダをスキャンします。", .zh: "选择宗卷，或扫描任意文件夹。", .pt: "Escolha um volume ou analise qualquer pasta."]) }
    static func scannedIn(_ files: Int, _ seconds: String) -> String { L("\(files) files in \(seconds) s", [.ru: "Файлов: \(files) за \(seconds) с", .es: "\(files) archivos en \(seconds) s", .fr: "\(files) fichiers en \(seconds) s", .de: "\(files) Dateien in \(seconds) s", .ja: "\(files) ファイル / \(seconds) 秒", .zh: "\(files) 个文件，\(seconds) 秒", .pt: "\(files) arquivos em \(seconds) s"]) }
    static func removedFreed(_ size: String) -> String { L("Removed — \(size) freed", [.ru: "Удалено — освобождено \(size)", .es: "Eliminado — \(size) liberados", .fr: "Supprimé — \(size) libérés", .de: "Entfernt — \(size) frei", .ja: "削除しました — \(size) を解放", .zh: "已删除 — 释放 \(size)", .pt: "Removido — \(size) liberados"]) }
    static func confirmTrash(_ count: Int, _ size: String) -> String {
        let items = Plural.items(count, language: AppLanguage.current.rawValue)
        return L("Move \(items) (\(size)) to the Trash?", [.ru: "Переместить \(items) (\(size)) в Корзину?", .es: "¿Mover \(items) (\(size)) a la Papelera?", .fr: "Déplacer \(items) (\(size)) vers la corbeille ?", .de: "\(items) (\(size)) in den Papierkorb legen?", .ja: "\(items)（\(size)）をゴミ箱に入れますか？", .zh: "将\(items)（\(size)）移到废纸篓？", .pt: "Mover \(items) (\(size)) para o Lixo?"])
    }
    static func measured(_ ago: String) -> String { L("Measured \(ago)", [.ru: "Измерено \(ago)", .es: "Medido \(ago)", .fr: "Mesuré \(ago)", .de: "Gemessen \(ago)", .ja: "計測 \(ago)", .zh: "测量于 \(ago)", .pt: "Medido \(ago)"]) }
    static var advice: String { L("Recommendations", [.ru: "Рекомендации", .es: "Recomendaciones", .fr: "Recommandations", .de: "Empfehlungen", .ja: "おすすめ", .zh: "建议", .pt: "Recomendações"]) }
    static var adviceHint: String { L("What could be deleted", [.ru: "Что можно удалить", .es: "Qué se podría eliminar", .fr: "Ce qui pourrait être supprimé", .de: "Was gelöscht werden könnte", .ja: "削除できる候補", .zh: "可删除的内容", .pt: "O que pode ser excluído"]) }
    static var adviceKindCache: String { L("Cache — safe to clear", [.ru: "Кеш — можно очистить", .es: "Caché — se puede limpiar", .fr: "Cache — peut être vidé", .de: "Cache — kann geleert werden", .ja: "キャッシュ — 削除可能", .zh: "缓存 — 可清理", .pt: "Cache — pode limpar"]) }
    static var adviceKindOldDownload: String { L("Old download", [.ru: "Старая загрузка", .es: "Descarga antigua", .fr: "Téléchargement ancien", .de: "Alter Download", .ja: "古いダウンロード", .zh: "旧下载", .pt: "Download antigo"]) }
    static var adviceKindLargeOld: String { L("Untouched for months", [.ru: "Не открывался месяцами", .es: "Sin abrir desde hace meses", .fr: "Inutilisé depuis des mois", .de: "Seit Monaten unberührt", .ja: "数か月間未使用", .zh: "数月未打开", .pt: "Sem uso há meses"]) }
    static var otherItems: String { L("Smaller items", [.ru: "Мелкие объекты", .es: "Elementos pequeños", .fr: "Petits éléments", .de: "Kleinere Objekte", .ja: "小さい項目", .zh: "较小的项目", .pt: "Itens menores"]) }
    static var duplicates: String { L("Duplicates", [.ru: "Дубликаты", .es: "Duplicados", .fr: "Doublons", .de: "Duplikate", .ja: "重複", .zh: "重复文件", .pt: "Duplicatas"]) }
    static var duplicatesHint: String { L("Find identical files in this folder", [.ru: "Найти одинаковые файлы в этой папке", .es: "Buscar archivos idénticos en esta carpeta", .fr: "Trouver les fichiers identiques dans ce dossier", .de: "Identische Dateien in diesem Ordner finden", .ja: "このフォルダ内の同一ファイルを探す", .zh: "在此文件夹中查找相同的文件", .pt: "Encontrar arquivos idênticos nesta pasta"]) }
    static var duplicatesTitle: String { L("A second look", [.ru: "Второй взгляд", .es: "Una segunda mirada", .fr: "Un second regard", .de: "Ein zweiter Blick", .ja: "もう一度チェック", .zh: "再看一眼", .pt: "Uma segunda olhada"]) }
    static func duplicatesSubtitle(_ folder: String) -> String { L("Files that exist more than once in “\(folder)”. Content compared, not names: same bytes, different places.", [.ru: "Файлы, которые существуют в «\(folder)» больше одного раза. Сравнивается содержимое, а не имена: одни и те же байты в разных местах.", .es: "Archivos que existen más de una vez en «\(folder)». Se compara el contenido, no los nombres: los mismos bytes en lugares distintos.", .fr: "Fichiers présents plus d’une fois dans « \(folder) ». C’est le contenu qui est comparé, pas les noms : les mêmes octets à des endroits différents.", .de: "Dateien, die in „\(folder)“ mehr als einmal existieren. Verglichen wird der Inhalt, nicht der Name: dieselben Bytes an verschiedenen Orten.", .ja: "「\(folder)」内に複数存在するファイル。名前ではなく内容を比較します。同じバイト列が別の場所にあるものです。", .zh: "在“\(folder)”中存在多份的文件。比较的是内容而非文件名：相同的字节，不同的位置。", .pt: "Arquivos que existem mais de uma vez em “\(folder)”. O conteúdo é comparado, não os nomes: os mesmos bytes em lugares diferentes."]) }
    static var duplicatesSearching: String { L("Reading files…", [.ru: "Чтение файлов…", .es: "Leyendo archivos…", .fr: "Lecture des fichiers…", .de: "Dateien werden gelesen…", .ja: "ファイルを読み込み中…", .zh: "正在读取文件…", .pt: "Lendo arquivos…"]) }
    static func duplicatesProgress(_ done: Int, _ total: Int) -> String { L("\(done) of \(total) candidates checked", [.ru: "Проверено \(done) из \(total) кандидатов", .es: "\(done) de \(total) candidatos comprobados", .fr: "\(done) candidats sur \(total) vérifiés", .de: "\(done) von \(total) Kandidaten geprüft", .ja: "\(done) / \(total) 件を確認済み", .zh: "已检查 \(done) / \(total) 个候选", .pt: "\(done) de \(total) candidatos verificados"]) }
    static var duplicatesNone: String { L("No duplicates here. Every large file under this folder is one of a kind.", [.ru: "Дубликатов нет. Каждый крупный файл в этой папке существует в единственном экземпляре.", .es: "No hay duplicados. Cada archivo grande de esta carpeta es único.", .fr: "Aucun doublon. Chaque gros fichier de ce dossier est unique.", .de: "Keine Duplikate. Jede große Datei in diesem Ordner gibt es genau einmal.", .ja: "重複はありません。このフォルダの大きなファイルはすべて 1 つだけです。", .zh: "没有重复文件。此文件夹下的每个大文件都只有一份。", .pt: "Sem duplicatas. Cada arquivo grande nesta pasta é único."]) }
    static var duplicatesFloorNote: String { L("Files from 1 MB. Hard links are one file and are never offered.", [.ru: "Файлы от 1 МБ. Жёсткие ссылки — это один файл, они не предлагаются.", .es: "Archivos desde 1 MB. Los enlaces duros son un solo archivo y nunca se ofrecen.", .fr: "Fichiers à partir de 1 Mo. Les liens durs sont un seul fichier et ne sont jamais proposés.", .de: "Dateien ab 1 MB. Harte Links sind eine Datei und werden nie angeboten.", .ja: "1 MB 以上のファイルが対象。ハードリンクは同一ファイルなので提案されません。", .zh: "1 MB 以上的文件。硬链接是同一个文件，不会被列出。", .pt: "Arquivos a partir de 1 MB. Links físicos são um só arquivo e nunca são oferecidos."]) }
    static func duplicatesFound(_ groups: Int, _ wasted: String) -> String { L("Groups: \(groups) · \(wasted) recoverable", [.ru: "Групп: \(groups) · можно освободить \(wasted)", .es: "Grupos: \(groups) · \(wasted) recuperables", .fr: "Groupes : \(groups) · \(wasted) récupérables", .de: "Gruppen: \(groups) · \(wasted) freizugeben", .ja: "\(groups) グループ · \(wasted) 解放可能", .zh: "\(groups) 组 · 可释放 \(wasted)", .pt: "Grupos: \(groups) · \(wasted) recuperáveis"]) }
    static func duplicatesPicked(_ count: Int, _ bytes: String) -> String { L("picked: \(count) (\(bytes))", [.ru: "отобрано: \(count) (\(bytes))", .es: "elegidos: \(count) (\(bytes))", .fr: "choisis : \(count) (\(bytes))", .de: "ausgewählt: \(count) (\(bytes))", .ja: "選択: \(count)（\(bytes)）", .zh: "已选 \(count) 个（\(bytes)）", .pt: "escolhidos: \(count) (\(bytes))"]) }
    static var duplicatesKeepWhy: String { L("The first path in alphabetical order. Helm never offers every copy of a file.", [.ru: "Первый путь по алфавиту. Helm никогда не предлагает удалить все копии файла.", .es: "La primera ruta en orden alfabético. Helm nunca ofrece todas las copias de un archivo.", .fr: "Le premier chemin par ordre alphabétique. Helm ne propose jamais toutes les copies d’un fichier.", .de: "Der alphabetisch erste Pfad. Helm bietet nie alle Kopien einer Datei an.", .ja: "アルファベット順で最初のパスです。Helm がすべてのコピーを削除対象にすることはありません。", .zh: "按字母顺序排在最前的路径。Helm 绝不会把文件的所有副本都列为可删。", .pt: "O primeiro caminho em ordem alfabética. O Helm nunca oferece todas as cópias de um arquivo."]) }
    static var duplicatesKeep: String { L("stays", [.ru: "останется", .es: "se queda", .fr: "reste", .de: "bleibt", .ja: "残す", .zh: "保留", .pt: "fica"]) }
    static var duplicatesBasketRest: String { L("Extras to basket", [.ru: "Лишние — к удалению", .es: "Sobrantes a la cesta", .fr: "Les surplus au panier", .de: "Überzählige in den Korb", .ja: "余分をバスケットへ", .zh: "多余的放入收集篮", .pt: "Excedentes para a cesta"]) }
    static var duplicatesClose: String { L("Close", [.ru: "Закрыть", .es: "Cerrar", .fr: "Fermer", .de: "Schließen", .ja: "閉じる", .zh: "关闭", .pt: "Fechar"]) }
    static var ringMap: String { L("Disk map", [.ru: "Карта диска", .es: "Mapa del disco", .fr: "Carte du disque", .de: "Festplattenkarte", .ja: "ディスクマップ", .zh: "磁盘分布图", .pt: "Mapa do disco"]) }
    static var openFolder: String { L("Open", [.ru: "Открыть", .es: "Abrir", .fr: "Ouvrir", .de: "Öffnen", .ja: "開く", .zh: "打开", .pt: "Abrir"]) }
    static var goUp: String { L("Go up a level", [.ru: "На уровень выше", .es: "Subir un nivel", .fr: "Remonter d’un niveau", .de: "Eine Ebene höher", .ja: "ひとつ上の階層へ", .zh: "返回上一层", .pt: "Subir um nível"]) }
    static func ringShare(_ name: String, _ size: String, _ percent: Int) -> String { L("\(name), \(size), \(percent)% of this folder", [.ru: "\(name), \(size), \(percent)% этой папки", .es: "\(name), \(size), \(percent)% de esta carpeta", .fr: "\(name), \(size), \(percent) % de ce dossier", .de: "\(name), \(size), \(percent) % dieses Ordners", .ja: "\(name)、\(size)、このフォルダの \(percent)%", .zh: "\(name)，\(size)，占此文件夹 \(percent)%", .pt: "\(name), \(size), \(percent)% desta pasta"]) }
    static var back: String { L("Back", [.ru: "Назад", .es: "Atrás", .fr: "Retour", .de: "Zurück", .ja: "戻る", .zh: "返回", .pt: "Voltar"]) }
    static func liveCount(_ files: Int) -> String { L("\(files) files", [.ru: "Файлов: \(files)", .es: "\(files) archivos", .fr: "\(files) fichiers", .de: "\(files) Dateien", .ja: "\(files) ファイル", .zh: "\(files) 个文件", .pt: "\(files) arquivos"]) }
}
